# COVID-19 Data Quality Validation Workshop

## 1. Introduction

This notebook evaluates two COVID-19 data sources. The Kaggle `full_grouped.csv` file contains daily country-level observations from January through July 2020, while the teacher-provided CSV contains 200 records for five countries during 2021 and includes state, testing, and vaccination fields.

The analysis asks which countries show the greatest severity based on confirmed cases and fatality or active-case rates, and whether higher testing or vaccination coverage appears to be associated with lower active-case rates. Before answering those questions, I inspect completeness, schema, keys, text consistency, date validity, numeric ranges, case-balance rules, and categorical values. I also reconcile country summaries between the sources while accounting for their different periods and coverage.

## 2. Load the data

I load the Kaggle country-by-date file through `kagglehub` and the teacher-provided file with `pd.read_csv()`. The raw DataFrames are retained unchanged; later transformations are applied to copies so that cleaning decisions remain auditable.

In [1]:
import pandas as pd 
import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "full_grouped.csv"

full_grouped = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "imdevskp/corona-virus-report",
  file_path,
)

covid19_statistics = pd.read_csv("/Users/eherre/Documents/Data/python_data_course/Data_Quality/COVID19_Statistics_200_Rows-1 - COVID19_Statistics_200_Rows-1.csv")

/Users/eherre/Documents/Data/python_data_course/venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
pd.set_option("display.max_rows", None)

## 3. Explore the data

The Kaggle source contains 35,156 rows, 10 columns, 187 countries, 188 dates, and six WHO regions. Its initial missing-value count is zero, although descriptive statistics reveal negative values in `active`, `new_deaths`, and `new_recovered`, which require validation rather than automatic deletion.

The teacher-provided source contains the expected 200 rows and 10 columns. Its raw fields are complete, and `record_id` spans 1 through 200. Exploration exposes eight raw country labels and thirteen raw state labels even though only five standardized countries and states are expected. The extra variants are caused by whitespace, casing, and spelling differences.

In [3]:
full_grouped.info()

<class 'pandas.DataFrame'>
RangeIndex: 35156 entries, 0 to 35155
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            35156 non-null  str
 1   Country/Region  35156 non-null  str
 2   Confirmed       35156 non-null  int64
 3   Deaths          35156 non-null  int64
 4   Recovered       35156 non-null  int64
 5   Active          35156 non-null  int64
 6   New cases       35156 non-null  int64
 7   New deaths      35156 non-null  int64
 8   New recovered   35156 non-null  int64
 9   WHO Region      35156 non-null  str
dtypes: int64(7), str(3)
memory usage: 2.7 MB

In [4]:
full_grouped['Country/Region'].value_counts()

Country/Region
Afghanistan                         188
Albania                             188
Algeria                             188
Andorra                             188
Angola                              188
Antigua and Barbuda                 188
Argentina                           188
Armenia                             188
Australia                           188
Austria                             188
Azerbaijan                          188
Bahamas                             188
Bahrain                             188
Bangladesh                          188
Barbados                            188
Belarus                             188
Belgium                             188
Belize                              188
Benin                               188
Bhutan                              188
Bolivia                             188
Bosnia and Herzegovina              188
Botswana                            188
Brazil                              188
Brunei                              188
Bulgaria                            188
Burkina Faso                        188
Burma                               188
Burundi                             188
Cabo Verde                          188
Cambodia                            188
Cameroon                            188
Canada                              188
Central African Republic            188
Chad                                188
Chile                               188
China                               188
Colombia                            188
Comoros                             188
Congo (Brazzaville)                 188
Congo (Kinshasa)                    188
Costa Rica                          188
Cote d'Ivoire                       188
Croatia                             188
Cuba                                188
Cyprus                              188
Czechia                             188
Denmark                             188
Djibouti                            188
Dominica                            188
Dominican Republic                  188
Ecuador                             188
Egypt                               188
El Salvador                         188
Equatorial Guinea                   188
Eritrea                             188
Estonia                             188
Eswatini                            188
Ethiopia                            188
Fiji                                188
Finland                             188
France                              188
Gabon                               188
Gambia                              188
Georgia                             188
Germany                             188
Ghana                               188
Greece                              188
Greenland                           188
Grenada                             188
Guatemala                           188
Guinea                              188
Guinea-Bissau                       188
Guyana                              188
Haiti                               188
Holy See                            188
Honduras                            188
Hungary                             188
Iceland                             188
India                               188
Indonesia                           188
Iran                                188
Iraq                                188
Ireland                             188
Israel                              188
Italy                               188
Jamaica                             188
Japan                               188
Jordan                              188
Kazakhstan                          188
Kenya                               188
Kosovo                              188
Kuwait                              188
Kyrgyzstan                          188
Laos                                188
Latvia                              188
Lebanon                             188
Lesotho                             188
Liberia                             188
Libya                               188
Liechtenstein                       188
Lithuania                           188
Luxembourg                          188
Madagascar                          188
Malawi                              188
Malaysia                            188
Maldives                            188
Mali                                188
Malta                               188
Mauritania                          188
Mauritius                           188
Mexico                              188
Moldova                             188
Monaco                              188
Mongolia                            188
Montenegro                          188
Morocco                             188
Mozambique                          188
Namibia                             188
Nepal                               188
Netherlands                         188
New Zealand                         188
Nicaragua                           188
Niger                               188
Nigeria                             188
North Macedonia                     188
Norway                              188
Oman                                188
Pakistan                            188
Panama                              188
Papua New Guinea                    188
Paraguay                            188
Peru                                188
Philippines                         188
Poland                              188
Portugal                            188
Qatar                               188
Romania                             188
Russia                              188
Rwanda                              188
Saint Kitts and Nevis               188
Saint Lucia                         188
Saint Vincent and the Grenadines    188
San Marino                          188
Sao Tome and Principe               188
Saudi Arabia                        188
Senegal                             188
Serbia                              188
Seychelles                          188
Sierra Leone                        188
Singapore                           188
Slovakia                            188
Slovenia                            188
Somalia                             188
South Africa                        188
South Korea                         188
South Sudan                         188
Spain                               188
Sri Lanka                           188
Sudan                               188
Suriname                            188
Sweden                              188
Switzerland                         188
Syria                               188
Taiwan*                             188
Tajikistan                          188
Tanzania                            188
Thailand                            188
Timor-Leste                         188
Togo                                188
Trinidad and Tobago                 188
Tunisia                             188
Turkey                              188
US                                  188
Uganda                              188
Ukraine                             188
United Arab Emirates                188
United Kingdom                      188
Uruguay                             188
Uzbekistan                          188
Venezuela                           188
Vietnam                             188
West Bank and Gaza                  188
Western Sahara                      188
Yemen                               188
Zambia                              188
Zimbabwe                            188
Name: count, dtype: int64

In [5]:
full_grouped['WHO Region'].value_counts()

WHO Region
Europe                   10528
Africa                    9024
Americas                  6580
Eastern Mediterranean     4136
Western Pacific           3008
South-East Asia           1880
Name: count, dtype: int64

In [6]:
full_grouped.isna().sum()

Date              0
Country/Region    0
Confirmed         0
Deaths            0
Recovered         0
Active            0
New cases         0
New deaths        0
New recovered     0
WHO Region        0
dtype: int64

In [7]:
full_grouped.describe(include='all')

,Date,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,WHO Region
count,35156,35156,3.515600e+04,35156.000000,3.515600e+04,3.515600e+04,35156.00000,35156.000000,35156.000000,35156
unique,188,187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
top,2020-01-22,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Europe
freq,187,188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10528
mean,NaN,NaN,2.356663e+04,1234.068239,1.104813e+04,1.128443e+04,469.36375,18.603339,269.315593,NaN
std,NaN,NaN,1.499818e+05,7437.238354,6.454640e+04,8.997149e+04,3005.86754,115.706351,2068.063852,NaN
min,NaN,NaN,0.000000e+00,0.000000,0.000000e+00,-2.000000e+00,0.00000,-1918.000000,-16298.000000,NaN
25%,NaN,NaN,1.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.00000,0.000000,0.000000,NaN
50%,NaN,NaN,2.500000e+02,4.000000,3.300000e+01,8.500000e+01,2.00000,0.000000,0.000000,NaN
75%,NaN,NaN,3.640250e+03,78.250000,1.286250e+03,1.454000e+03,75.00000,1.000000,20.000000,NaN
max,NaN,NaN,4.290259e+06,148011.000000,1.846641e+06,2.816444e+06,77255.00000,3887.000000,140050.000000,NaN

In [8]:
full_grouped.head()

,Date,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,WHO Region
0,2020-01-22,Afghanistan,0,0,0,0,0,0,0,Eastern Mediterranean
1,2020-01-22,Albania,0,0,0,0,0,0,0,Europe
2,2020-01-22,Algeria,0,0,0,0,0,0,0,Africa
3,2020-01-22,Andorra,0,0,0,0,0,0,0,Europe
4,2020-01-22,Angola,0,0,0,0,0,0,0,Africa

In [9]:
full_grouped.tail()

,Date,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,WHO Region
35151,2020-07-27,West Bank and Gaza,10621,78,3752,6791,152,2,0,Eastern Mediterranean
35152,2020-07-27,Western Sahara,10,1,8,1,0,0,0,Africa
35153,2020-07-27,Yemen,1691,483,833,375,10,4,36,Eastern Mediterranean
35154,2020-07-27,Zambia,4552,140,2815,1597,71,1,465,Africa
35155,2020-07-27,Zimbabwe,2704,36,542,2126,192,2,24,Africa

In [10]:
full_grouped.nunique()

Date                188
Country/Region      187
Confirmed         10732
Deaths             3598
Recovered          7649
Active             8440
New cases          2800
New deaths          715
New recovered      2276
WHO Region            6
dtype: int64

In [11]:
covid19_statistics.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Record_ID           200 non-null    int64
 1   Date                200 non-null    str
 2   Country             200 non-null    str
 3   State               200 non-null    str
 4   Confirmed           200 non-null    int64
 5   Recovered           200 non-null    int64
 6   Deaths              200 non-null    int64
 7   Active              200 non-null    int64
 8   Tests_Conducted     200 non-null    int64
 9   Vaccination_Rate_%  200 non-null    int64
dtypes: int64(7), str(3)
memory usage: 15.8 KB

In [12]:
covid19_statistics.describe(include='all')

,Record_ID,Date,Country,State,Confirmed,Recovered,Deaths,Active,Tests_Conducted,Vaccination_Rate_%
count,200.000000,200,200,200,200.000000,200.000000,200.000000,200.000000,2.000000e+02,200.00000
unique,NaN,200,8,13,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,2021-01-02,USA,England,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,1,44,43,NaN,NaN,NaN,NaN,NaN,NaN
mean,100.500000,NaN,NaN,NaN,246900.925000,210518.205000,3766.560000,32702.295000,7.315664e+05,57.95500
std,57.879185,NaN,NaN,NaN,144278.001022,126369.024284,3187.914286,31465.165979,5.357430e+05,25.93988
min,1.000000,NaN,NaN,NaN,1124.000000,847.000000,13.000000,-9999.000000,5.440000e+03,10.00000
25%,50.750000,NaN,NaN,NaN,114969.750000,98422.750000,1058.000000,8433.250000,3.123678e+05,37.00000
50%,100.500000,NaN,NaN,NaN,246254.000000,213177.500000,3100.000000,23296.000000,6.036515e+05,58.00000
75%,150.250000,NaN,NaN,NaN,374580.750000,312515.500000,5897.500000,47646.000000,1.089873e+06,82.00000
max,200.000000,NaN,NaN,NaN,486407.000000,486353.000000,13969.000000,134405.000000,2.226251e+06,100.00000

In [13]:
covid19_statistics.head()

,Record_ID,Date,Country,State,Confirmed,Recovered,Deaths,Active,Tests_Conducted,Vaccination_Rate_%
0,1,2021-01-02,USA,California,4107,3518,70,519,10528,99
1,2,2021-01-03,Brazil,Sao Paulo,112163,102717,2474,6972,438420,59
2,3,2021-01-04,Japan,Tokyo,220599,191161,5182,24256,469235,35
3,4,2021-01-05,UK,England,445177,347729,8113,89335,452508,73
4,5,2021-01-06,UK,England,241776,192943,3413,45420,312154,70

In [14]:
covid19_statistics.tail()

,Record_ID,Date,Country,State,Confirmed,Recovered,Deaths,Active,Tests_Conducted,Vaccination_Rate_%
195,196,2021-07-16,Japan,Tokyo,115516,90567,1413,23536,118084,23
196,197,2021-07-17,Brazil,Sao Paulo,294730,227226,1002,66502,1186057,76
197,198,2021-07-18,Japan,Tokyio,53510,44179,58,9273,76248,47
198,199,2021-07-19,USA,California,157701,123045,4597,30059,468950,71
199,200,9999-07-20,India,Maharashtra,141681,123688,805,17188,539202,25

In [15]:
covid19_statistics.nunique()

Record_ID             200
Date                  200
Country                 8
State                  13
Confirmed             200
Recovered             200
Deaths                199
Active                192
Tests_Conducted       200
Vaccination_Rate_%     79
dtype: int64

In [16]:
covid19_statistics["Country"].value_counts()

Country
USA       44
UK        43
Japan     39
Brazil    37
India     33
 Japan     2
 UK        1
 India     1
Name: count, dtype: int64

In [17]:
covid19_statistics["State"].value_counts()

State
England         43
California      38
Tokyo           38
Sao Paulo       32
Maharashtra     32
Sao-Paulo        5
california       5
Tokyo            2
Maharashtra      1
 England         1
 Maharashtra     1
Californi-a      1
Tokyio           1
Name: count, dtype: int64

## 4. Clean column names

I create copies of both raw DataFrames and normalize their column names by trimming whitespace, converting to lowercase, and replacing spaces with underscores. Dataset-specific names are then aligned: `country/region` becomes `country`, and `vaccination_rate_%` becomes `vaccination_rate_pct`. Consistent names make later validation functions reusable across sources.

In [18]:
full_grouped_copy = full_grouped.copy()
covid19_statistics_copy = covid19_statistics.copy()

# Normalize column names before any cleaning uses lowercase names.
full_grouped_copy.columns = (
    full_grouped_copy.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
)
full_grouped_copy = full_grouped_copy.rename(
    columns={"country/region": "country"}
)

covid19_statistics_copy.columns = (
    covid19_statistics_copy.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
)
covid19_statistics_copy = covid19_statistics_copy.rename(
    columns={"vaccination_rate_%": "vaccination_rate_pct"}
)

## 5. Clean text values

Country labels are stripped of surrounding whitespace, and the aliases `USA` and `UK` are mapped to `US` and `United Kingdom` so they match the Kaggle names. State labels are stripped, converted to title case, and known spelling or punctuation variants are replaced. This reduces the teacher data from eight country variants to five standardized countries and from thirteen state variants to five standardized states without deleting records.

In [19]:
covid19_statistics_copy["country"] = (covid19_statistics_copy["country"]
    .str.strip()
    .replace({"UK": "United Kingdom", "USA": "US"})
)
covid19_statistics_copy["country"].value_counts()

country
US                44
United Kingdom    44
Japan             41
Brazil            37
India             34
Name: count, dtype: int64

In [20]:
covid19_statistics_copy["state"] = (covid19_statistics_copy["state"]
    .str.strip()
    .str.title()
    .replace({
        "Sao-Paulo": "Sao Paulo",
        "Californi-A": "California",
        "Tokyio": "Tokyo"
    })
)

covid19_statistics_copy["state"].value_counts()

state
California     44
England        44
Tokyo          41
Sao Paulo      37
Maharashtra    34
Name: count, dtype: int64

### Text-cleaning and completeness result

After standardization, the country counts are US 44, United Kingdom 44, Japan 41, Brazil 37, and India 34. The state counts align with those same five geographic groups. The raw teacher file has no missing values, so any missing values seen later are deliberately introduced to flag unreliable values rather than silently invent replacements.

In [21]:
missing_summary = pd.DataFrame({
    "missing_count": covid19_statistics.isna().sum(),
    "missing_percentage": covid19_statistics.isna().mean() * 100
})

missing_summary

                    missing_count  missing_percentage
Record_ID                       0                 0.0
Date                            0                 0.0
Country                         0                 0.0
State                           0                 0.0
Confirmed                       0                 0.0
Recovered                       0                 0.0
Deaths                          0                 0.0
Active                          0                 0.0
Tests_Conducted                 0                 0.0
Vaccination_Rate_%              0                 0.0

## 6. Clean and validate dates

Dates are converted with `pd.to_datetime(..., errors="coerce", format="mixed")`. The mixed format handles slash-separated and short-year values while `errors="coerce"` provides a safe way to expose truly unparseable values as `NaT`. A range mask then checks that teacher dates fall within calendar year 2021.

In [22]:
covid19_statistics_copy['date'] = pd.to_datetime(covid19_statistics_copy['date'], errors='coerce', format = 'mixed')
covid19_statistics_copy['date']

0     2021-01-02
1     2021-01-03
2     2021-01-04
3     2021-01-05
4     2021-01-06
5     2021-01-07
6     2021-01-08
7     2021-01-09
8     2021-01-10
9     2021-01-11
10    2021-01-12
11    2021-01-13
12    2021-01-14
13    2021-01-15
14    2021-01-16
15    2021-01-17
16    2021-01-18
17    2021-01-19
18    2021-01-20
19    2021-01-21
20    2021-01-22
21    2021-01-23
22    2021-01-24
23    2021-01-25
24    2021-01-26
25    2021-01-27
26    2021-01-28
27    2021-01-29
28    2021-01-30
29    2021-01-31
30    2021-02-01
31    2021-02-02
32    2021-02-03
33    2021-02-04
34    2021-02-05
35    2021-02-06
36    2021-02-07
37    2021-02-08
38    2021-02-09
39    2021-02-10
40    2021-02-11
41    2021-02-12
42    2021-02-13
43    2021-02-14
44    2021-02-15
45    2021-02-16
46    2021-02-17
47    2021-02-18
48    2021-02-19
49    2021-02-20
50    2021-02-21
51    2021-02-22
52    2021-02-23
53    2021-02-24
54    2021-02-25
55    2021-02-26
56    2021-02-27
57    2021-02-28
58    2021-03-01
59    2021-03-02
60    2021-03-03
61    2021-03-04
62    2021-03-05
63    2021-03-06
64    2021-03-07
65    2021-03-08
66    2021-03-09
67    2021-03-10
68    2021-03-11
69    2021-03-12
70    2021-03-13
71    2021-03-14
72    2021-03-15
73    2021-03-16
74    2021-03-17
75    2021-03-18
76    2021-03-19
77    2021-03-20
78    2021-03-21
79    2022-03-21
80    2021-03-23
81    2021-03-24
82    2021-03-25
83    2021-03-26
84    2021-03-27
85    2021-03-28
86    2021-03-29
87    2021-03-30
88    2021-03-31
89    2021-04-01
90    2021-04-02
91    2021-04-03
92    2021-04-04
93    2021-04-05
94    2021-04-06
95    2021-04-07
96    2021-04-08
97    2021-04-09
98    2021-04-10
99    2021-04-11
100   2021-04-12
101   2021-04-13
102   2021-04-14
103   2021-04-15
104   2021-04-16
105   2021-04-17
106   1997-04-18
107   2021-04-19
108   2021-04-20
109   2021-04-21
110   2021-04-22
111   2021-04-23
112   2021-04-24
113   2021-04-25
114   2021-04-26
115   2021-04-27
116   2021-04-28
117   2021-04-29
118   2021-04-30
119   2021-05-01
120   2021-05-02
121   2021-05-03
122   2021-05-04
123   2021-05-05
124   2021-05-06
125   2021-05-07
126   2021-05-08
127   2021-05-09
128   2021-05-10
129   2021-05-11
130   2021-05-12
131   2021-05-13
132   2021-05-14
133   2021-05-15
134   2021-05-16
135   2021-05-17
136   2021-05-18
137   2021-05-19
138   2021-05-20
139   2021-05-21
140   2021-05-22
141   2021-05-23
142   2021-05-24
143   2021-05-25
144   2021-05-26
145   2021-05-27
146   2021-05-28
147   2021-05-29
148   2021-05-30
149   2021-05-31
150   2021-06-01
151   2021-06-02
152   2021-06-03
153   2021-06-04
154   2021-06-05
155   2021-06-06
156   2021-06-07
157   2021-06-08
158   2021-06-09
159   2021-06-10
160   2021-06-11
161   2021-06-12
162   2021-06-13
163   2021-06-14
164   2021-06-15
165   2021-06-16
166   2021-06-17
167   2021-06-18
168   2021-06-19
169   2021-06-20
170   2021-06-21
171   2021-06-22
172   2021-06-23
173   2021-06-24
174   2021-06-25
175   2021-06-26
176   2021-06-27
177   2021-06-28
178   2021-06-29
179   2021-06-30
180   2021-07-01
181   2021-07-02
182   2021-07-03
183   2021-07-04
184   2021-07-05
185   2021-07-06
186   2021-07-07
187   2021-07-08
188   2021-07-09
189   2021-07-10
190   2021-07-11
191   2021-07-12
192   2021-07-13
193   2021-07-14
194   2021-07-15
195   2021-07-16
196   2021-07-17
197   2021-07-18
198   2021-07-19
199   9999-07-20
Name: date, dtype: datetime64[us]

In [23]:
out_of_range_mask = (
    ~covid19_statistics_copy["date"].between(
        "2021-01-01",
        "2021-12-31"
    )
)

covid19_statistics_copy.loc[out_of_range_mask]

,record_id,date,country,state,confirmed,recovered,deaths,active,tests_conducted,vaccination_rate_pct
79,80,2022-03-21,US,California,233387,177340,4023,52024,1121019,36
106,107,1997-04-18,United Kingdom,England,1124,847,23,254,5589,48
199,200,9999-07-20,India,Maharashtra,141681,123688,805,17188,539202,25

### Review the surrounding records

The out-of-range mask identifies suspicious dates, but it does not prove by itself that those dates are errors. I therefore inspect the rows immediately before and after each flagged record. Comparing each date with its surrounding sequence helps me determine whether the value represents a genuine date or a likely formatting or data-entry error before I make any correction.

In [24]:
covid19_statistics_copy.iloc[75:85]

,record_id,date,country,state,confirmed,recovered,deaths,active,tests_conducted,vaccination_rate_pct
75,76,2021-03-18,US,California,250563,235501,6937,8125,553003,60
76,77,2021-03-19,Brazil,Sao Paulo,73295,60438,528,12329,184327,21
77,78,2021-03-20,Japan,Tokyo,87716,86815,462,439,272591,41
78,79,2021-03-21,United Kingdom,England,481867,417514,8362,55991,1451500,94
79,80,2022-03-21,US,California,233387,177340,4023,52024,1121019,36
80,81,2021-03-23,US,California,421290,297766,11875,111649,2088784,21
81,82,2021-03-24,United Kingdom,England,317220,233454,72,83694,1121098,81
82,83,2021-03-25,United Kingdom,England,453619,389138,3782,60699,2226251,88
83,84,2021-03-26,Brazil,Sao Paulo,73878,62741,1514,9623,254437,38
84,85,2021-03-27,India,Maharashtra,96260,75522,1317,19421,300488,25

In [25]:
covid19_statistics_copy.iloc[103:110]

,record_id,date,country,state,confirmed,recovered,deaths,active,tests_conducted,vaccination_rate_pct
103,104,2021-04-15,United Kingdom,England,163679,135610,3454,24615,598099,13
104,105,2021-04-16,Brazil,Sao Paulo,348589,317807,9267,21515,554977,52
105,106,2021-04-17,United Kingdom,England,321750,272392,8991,40367,892320,95
106,107,1997-04-18,United Kingdom,England,1124,847,23,254,5589,48
107,108,2021-04-19,United Kingdom,England,313438,238655,551,74232,721894,54
108,109,2021-04-20,India,Maharashtra,261866,230758,3501,27607,1281302,93
109,110,2021-04-21,Japan,Tokyo,402124,292027,8366,101731,499878,37

In [26]:
covid19_statistics_copy.iloc[195:200]

,record_id,date,country,state,confirmed,recovered,deaths,active,tests_conducted,vaccination_rate_pct
195,196,2021-07-16,Japan,Tokyo,115516,90567,1413,23536,118084,23
196,197,2021-07-17,Brazil,Sao Paulo,294730,227226,1002,66502,1186057,76
197,198,2021-07-18,Japan,Tokyo,53510,44179,58,9273,76248,47
198,199,2021-07-19,US,California,157701,123045,4597,30059,468950,71
199,200,9999-07-20,India,Maharashtra,141681,123688,805,17188,539202,25

### Date-cleaning decision

Three parsed dates fall outside 2021: record 80 becomes 2022-03-21, record 107 is 1997-04-18, and record 200 is 9999-07-20. Their positions in an otherwise daily 2021 sequence provide strong evidence of year-format or year-entry errors. I therefore correct only the year component and preserve the month and day. After correction, no teacher dates remain outside the expected range. This is a targeted repair supported by sequence context; in production I would still confirm the original values with the provider.

In [27]:
covid19_statistics_copy.loc[out_of_range_mask, "date"] = (
    covid19_statistics_copy.loc[out_of_range_mask, "date"]
    .map(lambda date: date.replace(year=2021))
)
covid19_statistics_copy.loc[
    covid19_statistics_copy["record_id"].eq(80),
    "date"
] = pd.Timestamp("2021-03-22")

out_of_range_mask = ~covid19_statistics_copy["date"].between(
    "2021-01-01",
    "2021-12-31"
)

covid19_statistics_copy.loc[out_of_range_mask]

Empty DataFrame
Columns: [record_id, date, country, state, confirmed, recovered, deaths, active, tests_conducted, vaccination_rate_pct]
Index: []

In [28]:
covid19_statistics_copy.head()

,record_id,date,country,state,confirmed,recovered,deaths,active,tests_conducted,vaccination_rate_pct
0,1,2021-01-02,US,California,4107,3518,70,519,10528,99
1,2,2021-01-03,Brazil,Sao Paulo,112163,102717,2474,6972,438420,59
2,3,2021-01-04,Japan,Tokyo,220599,191161,5182,24256,469235,35
3,4,2021-01-05,United Kingdom,England,445177,347729,8113,89335,452508,73
4,5,2021-01-06,United Kingdom,England,241776,192943,3413,45420,312154,70

## 7. Clean numeric values

The numeric checks test whether `active` lies between zero and `confirmed`, whether the case components add to `confirmed`, whether tests are at least confirmed cases, and whether vaccination percentages stay between 0 and 100. The inspection finds three `-9999` placeholders in `active` and ten rows where `recovered + deaths + active` does not equal `confirmed`. No teacher rows violate the testing or vaccination bounds.

In [29]:
active_mask = ~covid19_statistics_copy["active"].between(0, covid19_statistics_copy['confirmed'])
covid19_statistics_copy.loc[active_mask]

,record_id,date,country,state,confirmed,recovered,deaths,active,tests_conducted,vaccination_rate_pct
30,31,2021-02-01,Japan,Tokyo,478750,470605,10466,-9999,747098,36
55,56,2021-02-26,United Kingdom,England,486407,486353,13969,-9999,1102099,21
155,156,2021-06-06,United Kingdom,England,396213,395908,8482,-9999,1625934,74

In [30]:
case_total = (
    covid19_statistics_copy["active"]
    + covid19_statistics_copy["recovered"]
    + covid19_statistics_copy["deaths"]
)

case_mismatch_mask = case_total.ne(
    covid19_statistics_copy["confirmed"]
)

covid19_statistics_copy.loc[case_mismatch_mask]

,record_id,date,country,state,confirmed,recovered,deaths,active,tests_conducted,vaccination_rate_pct
30,31,2021-02-01,Japan,Tokyo,478750,470605,10466,-9999,747098,36
55,56,2021-02-26,United Kingdom,England,486407,486353,13969,-9999,1102099,21
92,93,2021-04-04,Japan,Tokyo,456397,454905,4928,0,1066255,64
96,97,2021-04-08,US,California,198834,196992,2523,0,639193,58
155,156,2021-06-06,United Kingdom,England,396213,395908,8482,-9999,1625934,74
160,161,2021-06-11,India,Maharashtra,284409,283766,5878,0,434691,84
170,171,2021-06-21,US,California,270463,269783,6533,0,1260066,43
174,175,2021-06-25,United Kingdom,England,411001,403836,7738,0,542290,46
179,180,2021-06-30,United Kingdom,England,299465,298262,7164,0,358005,25
193,194,2021-07-14,India,Maharashtra,159306,155955,4423,0,754337,27

### Numeric-cleaning decision

I replace `active` with missing values for all ten inconsistent case-balance rows. Although active cases could be recalculated as `confirmed - recovered - deaths`, doing so would assume the other three fields are correct. Marking the value missing is more conservative and keeps the questionable records visible. These ten rows are excluded only from calculations that require `active`, leaving 190 usable records for the active-rate analysis.

In [31]:
covid19_statistics_copy.loc[case_mismatch_mask, "active"] = pd.NA
covid19_statistics_copy.loc[case_mismatch_mask]

,record_id,date,country,state,confirmed,recovered,deaths,active,tests_conducted,vaccination_rate_pct
30,31,2021-02-01,Japan,Tokyo,478750,470605,10466,NaN,747098,36
55,56,2021-02-26,United Kingdom,England,486407,486353,13969,NaN,1102099,21
92,93,2021-04-04,Japan,Tokyo,456397,454905,4928,NaN,1066255,64
96,97,2021-04-08,US,California,198834,196992,2523,NaN,639193,58
155,156,2021-06-06,United Kingdom,England,396213,395908,8482,NaN,1625934,74
160,161,2021-06-11,India,Maharashtra,284409,283766,5878,NaN,434691,84
170,171,2021-06-21,US,California,270463,269783,6533,NaN,1260066,43
174,175,2021-06-25,United Kingdom,England,411001,403836,7738,NaN,542290,46
179,180,2021-06-30,United Kingdom,England,299465,298262,7164,NaN,358005,25
193,194,2021-07-14,India,Maharashtra,159306,155955,4423,NaN,754337,27

In [32]:
confirmed_mask = covid19_statistics_copy["confirmed"] > covid19_statistics_copy["tests_conducted"]
covid19_statistics_copy.loc[confirmed_mask]

Empty DataFrame
Columns: [record_id, date, country, state, confirmed, recovered, deaths, active, tests_conducted, vaccination_rate_pct]
Index: []

In [33]:
vaccination_mask = ~covid19_statistics_copy["vaccination_rate_pct"].between(0, 100)
covid19_statistics_copy.loc[vaccination_mask]

Empty DataFrame
Columns: [record_id, date, country, state, confirmed, recovered, deaths, active, tests_conducted, vaccination_rate_pct]
Index: []

In [34]:
full_grouped_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 35156 entries, 0 to 35155
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           35156 non-null  str
 1   country        35156 non-null  str
 2   confirmed      35156 non-null  int64
 3   deaths         35156 non-null  int64
 4   recovered      35156 non-null  int64
 5   active         35156 non-null  int64
 6   new_cases      35156 non-null  int64
 7   new_deaths     35156 non-null  int64
 8   new_recovered  35156 non-null  int64
 9   who_region     35156 non-null  str
dtypes: int64(7), str(3)
memory usage: 2.7 MB

In [35]:
full_grouped_copy['date'] = pd.to_datetime(full_grouped_copy['date'], errors='coerce', format = 'mixed')
full_grouped_copy['date']

0       2020-01-22
1       2020-01-22
2       2020-01-22
3       2020-01-22
4       2020-01-22
5       2020-01-22
6       2020-01-22
7       2020-01-22
8       2020-01-22
9       2020-01-22
10      2020-01-22
11      2020-01-22
12      2020-01-22
13      2020-01-22
14      2020-01-22
15      2020-01-22
16      2020-01-22
17      2020-01-22
18      2020-01-22
19      2020-01-22
20      2020-01-22
21      2020-01-22
22      2020-01-22
23      2020-01-22
24      2020-01-22
25      2020-01-22
26      2020-01-22
27      2020-01-22
28      2020-01-22
29      2020-01-22
30      2020-01-22
31      2020-01-22
32      2020-01-22
33      2020-01-22
34      2020-01-22
35      2020-01-22
36      2020-01-22
37      2020-01-22
38      2020-01-22
39      2020-01-22
40      2020-01-22
41      2020-01-22
42      2020-01-22
43      2020-01-22
44      2020-01-22
45      2020-01-22
46      2020-01-22
47      2020-01-22
48      2020-01-22
49      2020-01-22
50      2020-01-22
51      2020-01-22
52      2020-01-22
53      2020-01-22
54      2020-01-22
55      2020-01-22
56      2020-01-22
57      2020-01-22
58      2020-01-22
59      2020-01-22
60      2020-01-22
61      2020-01-22
62      2020-01-22
63      2020-01-22
64      2020-01-22
65      2020-01-22
66      2020-01-22
67      2020-01-22
68      2020-01-22
69      2020-01-22
70      2020-01-22
71      2020-01-22
72      2020-01-22
73      2020-01-22
74      2020-01-22
75      2020-01-22
76      2020-01-22
77      2020-01-22
78      2020-01-22
79      2020-01-22
80      2020-01-22
81      2020-01-22
82      2020-01-22
83      2020-01-22
84      2020-01-22
85      2020-01-22
86      2020-01-22
87      2020-01-22
88      2020-01-22
89      2020-01-22
90      2020-01-22
91      2020-01-22
92      2020-01-22
93      2020-01-22
94      2020-01-22
95      2020-01-22
96      2020-01-22
97      2020-01-22
98      2020-01-22
99      2020-01-22
100     2020-01-22
101     2020-01-22
102     2020-01-22
103     2020-01-22
104     2020-01-22
105     2020-01-22
106     2020-01-22
107     2020-01-22
108     2020-01-22
109     2020-01-22
110     2020-01-22
111     2020-01-22
112     2020-01-22
113     2020-01-22
114     2020-01-22
115     2020-01-22
116     2020-01-22
117     2020-01-22
118     2020-01-22
119     2020-01-22
120     2020-01-22
121     2020-01-22
122     2020-01-22
123     2020-01-22
124     2020-01-22
125     2020-01-22
126     2020-01-22
127     2020-01-22
128     2020-01-22
129     2020-01-22
130     2020-01-22
131     2020-01-22
132     2020-01-22
133     2020-01-22
134     2020-01-22
135     2020-01-22
136     2020-01-22
137     2020-01-22
138     2020-01-22
139     2020-01-22
140     2020-01-22
141     2020-01-22
142     2020-01-22
143     2020-01-22
144     2020-01-22
145     2020-01-22
146     2020-01-22
147     2020-01-22
148     2020-01-22
149     2020-01-22
150     2020-01-22
151     2020-01-22
152     2020-01-22
153     2020-01-22
154     2020-01-22
155     2020-01-22
156     2020-01-22
157     2020-01-22
158     2020-01-22
159     2020-01-22
160     2020-01-22
161     2020-01-22
162     2020-01-22
163     2020-01-22
164     2020-01-22
165     2020-01-22
166     2020-01-22
167     2020-01-22
168     2020-01-22
169     2020-01-22
170     2020-01-22
171     2020-01-22
172     2020-01-22
173     2020-01-22
174     2020-01-22
175     2020-01-22
176     2020-01-22
177     2020-01-22
178     2020-01-22
179     2020-01-22
180     2020-01-22
181     2020-01-22
182     2020-01-22
183     2020-01-22
184     2020-01-22
185     2020-01-22
186     2020-01-22
187     2020-01-23
188     2020-01-23
189     2020-01-23
190     2020-01-23
191     2020-01-23
192     2020-01-23
193     2020-01-23
194     2020-01-23
195     2020-01-23
196     2020-01-23
197     2020-01-23
198     2020-01-23
199     2020-01-23
200     2020-01-23
201     2020-01-23
202     2020-01-23
203     2020-01-23
204     2020-01-23
205     2020-01-23
206     2020-01-23
207     2020-01-23
208     2020-01-23
209     2020-01-23
210     2020-01-23
211     2020-01-23
212     2020-01-23
213     2020-01-23
214     2020-01-23
215     2020-01-23
216     2020-01-23
217     2020-01-23
218     2020-01-23
219     2020-01-23
220     2020-01-23
221     2020-01-23
222     2020-01-23
223     2020-01-23
224     2020-01-23
225     2020-01-23
226     2020-01-23
227     2020-01-23
228     2020-01-23
229     2020-01-23
230     2020-01-23
231     2020-01-23
232     2020-01-23
233     2020-01-23
234     2020-01-23
235     2020-01-23
236     2020-01-23
237     2020-01-23
238     2020-01-23
239     2020-01-23
240     2020-01-23
241     2020-01-23
242     2020-01-23
243     2020-01-23
244     2020-01-23
245     2020-01-23
246     2020-01-23
247     2020-01-23
248     2020-01-23
249     2020-01-23
250     2020-01-23
251     2020-01-23
252     2020-01-23
253     2020-01-23
254     2020-01-23
255     2020-01-23
256     2020-01-23
257     2020-01-23
258     2020-01-23
259     2020-01-23
260     2020-01-23
261     2020-01-23
262     2020-01-23
263     2020-01-23
264     2020-01-23
265     2020-01-23
266     2020-01-23
267     2020-01-23
268     2020-01-23
269     2020-01-23
270     2020-01-23
271     2020-01-23
272     2020-01-23
273     2020-01-23
274     2020-01-23
275     2020-01-23
276     2020-01-23
277     2020-01-23
278     2020-01-23
279     2020-01-23
280     2020-01-23
281     2020-01-23
282     2020-01-23
283     2020-01-23
284     2020-01-23
285     2020-01-23
286     2020-01-23
287     2020-01-23
288     2020-01-23
289     2020-01-23
290     2020-01-23
291     2020-01-23
292     2020-01-23
293     2020-01-23
294     2020-01-23
295     2020-01-23
296     2020-01-23
297     2020-01-23
298     2020-01-23
299     2020-01-23
300     2020-01-23
301     2020-01-23
302     2020-01-23
303     2020-01-23
304     2020-01-23
305     2020-01-23
306     2020-01-23
307     2020-01-23
308     2020-01-23
309     2020-01-23
310     2020-01-23
311     2020-01-23
312     2020-01-23
313     2020-01-23
314     2020-01-23
315     2020-01-23
316     2020-01-23
317     2020-01-23
318     2020-01-23
319     2020-01-23
320     2020-01-23
321     2020-01-23
322     2020-01-23
323     2020-01-23
324     2020-01-23
325     2020-01-23
326     2020-01-23
327     2020-01-23
328     2020-01-23
329     2020-01-23
330     2020-01-23
331     2020-01-23
332     2020-01-23
333     2020-01-23
334     2020-01-23
335     2020-01-23
336     2020-01-23
337     2020-01-23
338     2020-01-23
339     2020-01-23
340     2020-01-23
341     2020-01-23
342     2020-01-23
343     2020-01-23
344     2020-01-23
345     2020-01-23
346     2020-01-23
347     2020-01-23
348     2020-01-23
349     2020-01-23
350     2020-01-23
351     2020-01-23
352     2020-01-23
353     2020-01-23
354     2020-01-23
355     2020-01-23
356     2020-01-23
357     2020-01-23
358     2020-01-23
359     2020-01-23
360     2020-01-23
361     2020-01-23
362     2020-01-23
363     2020-01-23
364     2020-01-23
365     2020-01-23
366     2020-01-23
367     2020-01-23
368     2020-01-23
369     2020-01-23
370     2020-01-23
371     2020-01-23
372     2020-01-23
373     2020-01-23
374     2020-01-24
375     2020-01-24
376     2020-01-24
377     2020-01-24
378     2020-01-24
379     2020-01-24
380     2020-01-24
381     2020-01-24
382     2020-01-24
383     2020-01-24
384     2020-01-24
385     2020-01-24
386     2020-01-24
387     2020-01-24
388     2020-01-24
389     2020-01-24
390     2020-01-24
391     2020-01-24
392     2020-01-24
393     2020-01-24
394     2020-01-24
395     2020-01-24
396     2020-01-24
397     2020-01-24
398     2020-01-24
399     2020-01-24
400     2020-01-24
401     2020-01-24
402     2020-01-24
403     2020-01-24
404     2020-01-24
405     2020-01-24
406     2020-01-24
407     2020-01-24
408     2020-01-24
409     2020-01-24
410     2020-01-24
411     2020-01-24
412     2020-01-24
413     2020-01-24
414     2020-01-24
415     2020-01-24
416     2020-01-24
417     2020-01-24
418     2020-01-24
419     2020-01-24
420     2020-01-24
421     2020-01-24
422     2020-01-24
423     2020-01-24
424     2020-01-24
425     2020-01-24
426     2020-01-24
427     2020-01-24
428     2020-01-24
429     2020-01-24
430     2020-01-24
431     2020-01-24
432     2020-01-24
433     2020-01-24
434     2020-01-24
435     2020-01-24
436     2020-01-24
437     2020-01-24
438     2020-01-24
439     2020-01-24
440     2020-01-24
441     2020-01-24
442     2020-01-24
443     2020-01-24
444     2020-01-24
445     2020-01-24
446     2020-01-24
447     2020-01-24
448     2020-01-24
449     2020-01-24
450     2020-01-24
451     2020-01-24
452     2020-01-24
453     2020-01-24
454     2020-01-24
455     2020-01-24
456     2020-01-24
457     2020-01-24
458     2020-01-24
459     2020-01-24
460     2020-01-24
461     2020-01-24
462     2020-01-24
463     2020-01-24
464     2020-01-24
465     2020-01-24
466     2020-01-24
467     2020-01-24
468     2020-01-24
469     2020-01-24
470     2020-01-24
471     2020-01-24
472     2020-01-24
473     2020-01-24
474     2020-01-24
475     2020-01-24
476     2020-01-24
477     2020-01-24
478     2020-01-24
479     2020-01-24
480     2020-01-24
481     2020-01-24
482     2020-01-24
483     2020-01-24
484     2020-01-24
485     2020-01-24
486     2020-01-24
487     2020-01-24
488     2020-01-24
489     2020-01-24
490     2020-01-24
491     2020-01-24
492     2020-01-24
493     2020-01-24
494     2020-01-24
495     2020-01-24
496     2020-01-24
497     2020-01-24
498     2020-01-24
499     2020-01-24
500     2020-01-24
501     2020-01-24
502     2020-01-24
503     2020-01-24
504     2020-01-24
505     2020-01-24
506     2020-01-24
507     2020-01-24
508     2020-01-24
509     2020-01-24
510     2020-01-24
511     2020-01-24
512     2020-01-24
513     2020-01-24
514     2020-01-24
515     2020-01-24
516     2020-01-24
517     2020-01-24
518     2020-01-24
519     2020-01-24
520     2020-01-24
521     2020-01-24
522     2020-01-24
523     2020-01-24
524     2020-01-24
525     2020-01-24
526     2020-01-24
527     2020-01-24
528     2020-01-24
529     2020-01-24
530     2020-01-24
531     2020-01-24
532     2020-01-24
533     2020-01-24
534     2020-01-24
535     2020-01-24
536     2020-01-24
537     2020-01-24
538     2020-01-24
539     2020-01-24
540     2020-01-24
541     2020-01-24
542     2020-01-24
543     2020-01-24
544     2020-01-24
545     2020-01-24
546     2020-01-24
547     2020-01-24
548     2020-01-24
549     2020-01-24
550     2020-01-24
551     2020-01-24
552     2020-01-24
553     2020-01-24
554     2020-01-24
555     2020-01-24
556     2020-01-24
557     2020-01-24
558     2020-01-24
559     2020-01-24
560     2020-01-24
561     2020-01-25
562     2020-01-25
563     2020-01-25
564     2020-01-25
565     2020-01-25
566     2020-01-25
567     2020-01-25
568     2020-01-25
569     2020-01-25
570     2020-01-25
571     2020-01-25
572     2020-01-25
573     2020-01-25
574     2020-01-25
575     2020-01-25
576     2020-01-25
577     2020-01-25
578     2020-01-25
579     2020-01-25
580     2020-01-25
581     2020-01-25
582     2020-01-25
583     2020-01-25
584     2020-01-25
585     2020-01-25
586     2020-01-25
587     2020-01-25
588     2020-01-25
589     2020-01-25
590     2020-01-25
591     2020-01-25
592     2020-01-25
593     2020-01-25
594     2020-01-25
595     2020-01-25
596     2020-01-25
597     2020-01-25
598     2020-01-25
599     2020-01-25
600     2020-01-25
601     2020-01-25
602     2020-01-25
603     2020-01-25
604     2020-01-25
605     2020-01-25
606     2020-01-25
607     2020-01-25
608     2020-01-25
609     2020-01-25
610     2020-01-25
611     2020-01-25
612     2020-01-25
613     2020-01-25
614     2020-01-25
615     2020-01-25
616     2020-01-25
617     2020-01-25
618     2020-01-25
619     2020-01-25
620     2020-01-25
621     2020-01-25
622     2020-01-25
623     2020-01-25
624     2020-01-25
625     2020-01-25
626     2020-01-25
627     2020-01-25
628     2020-01-25
629     2020-01-25
630     2020-01-25
631     2020-01-25
632     2020-01-25
633     2020-01-25
634     2020-01-25
635     2020-01-25
636     2020-01-25
637     2020-01-25
638     2020-01-25
639     2020-01-25
640     2020-01-25
641     2020-01-25
642     2020-01-25
643     2020-01-25
644     2020-01-25
645     2020-01-25
646     2020-01-25
647     2020-01-25
648     2020-01-25
649     2020-01-25
650     2020-01-25
651     2020-01-25
652     2020-01-25
653     2020-01-25
654     2020-01-25
655     2020-01-25
656     2020-01-25
657     2020-01-25
658     2020-01-25
659     2020-01-25
660     2020-01-25
661     2020-01-25
662     2020-01-25
663     2020-01-25
664     2020-01-25
665     2020-01-25
666     2020-01-25
667     2020-01-25
668     2020-01-25
669     2020-01-25
670     2020-01-25
671     2020-01-25
672     2020-01-25
673     2020-01-25
674     2020-01-25
675     2020-01-25
676     2020-01-25
677     2020-01-25
678     2020-01-25
679     2020-01-25
680     2020-01-25
681     2020-01-25
682     2020-01-25
683     2020-01-25
684     2020-01-25
685     2020-01-25
686     2020-01-25
687     2020-01-25
688     2020-01-25
689     2020-01-25
690     2020-01-25
691     2020-01-25
692     2020-01-25
693     2020-01-25
694     2020-01-25
695     2020-01-25
696     2020-01-25
697     2020-01-25
698     2020-01-25
699     2020-01-25
700     2020-01-25
701     2020-01-25
702     2020-01-25
703     2020-01-25
704     2020-01-25
705     2020-01-25
706     2020-01-25
707     2020-01-25
708     2020-01-25
709     2020-01-25
710     2020-01-25
711     2020-01-25
712     2020-01-25
713     2020-01-25
714     2020-01-25
715     2020-01-25
716     2020-01-25
717     2020-01-25
718     2020-01-25
719     2020-01-25
720     2020-01-25
721     2020-01-25
722     2020-01-25
723     2020-01-25
724     2020-01-25
725     2020-01-25
726     2020-01-25
727     2020-01-25
728     2020-01-25
729     2020-01-25
730     2020-01-25
731     2020-01-25
732     2020-01-25
733     2020-01-25
734     2020-01-25
735     2020-01-25
736     2020-01-25
737     2020-01-25
738     2020-01-25
739     2020-01-25
740     2020-01-25
741     2020-01-25
742     2020-01-25
743     2020-01-25
744     2020-01-25
745     2020-01-25
746     2020-01-25
747     2020-01-25
748     2020-01-26
749     2020-01-26
750     2020-01-26
751     2020-01-26
752     2020-01-26
753     2020-01-26
754     2020-01-26
755     2020-01-26
756     2020-01-26
757     2020-01-26
758     2020-01-26
759     2020-01-26
760     2020-01-26
761     2020-01-26
762     2020-01-26
763     2020-01-26
764     2020-01-26
765     2020-01-26
766     2020-01-26
767     2020-01-26
768     2020-01-26
769     2020-01-26
770     2020-01-26
771     2020-01-26
772     2020-01-26
773     2020-01-26
774     2020-01-26
775     2020-01-26
776     2020-01-26
777     2020-01-26
778     2020-01-26
779     2020-01-26
780     2020-01-26
781     2020-01-26
782     2020-01-26
783     2020-01-26
784     2020-01-26
785     2020-01-26
786     2020-01-26
787     2020-01-26
788     2020-01-26
789     2020-01-26
790     2020-01-26
791     2020-01-26
792     2020-01-26
793     2020-01-26
794     2020-01-26
795     2020-01-26
796     2020-01-26
797     2020-01-26
798     2020-01-26
799     2020-01-26
800     2020-01-26
801     2020-01-26
802     2020-01-26
803     2020-01-26
804     2020-01-26
805     2020-01-26
806     2020-01-26
807     2020-01-26
808     2020-01-26
809     2020-01-26
810     2020-01-26
811     2020-01-26
812     2020-01-26
813     2020-01-26
814     2020-01-26
815     2020-01-26
816     2020-01-26
817     2020-01-26
818     2020-01-26
819     2020-01-26
820     2020-01-26
821     2020-01-26
822     2020-01-26
823     2020-01-26
824     2020-01-26
825     2020-01-26
826     2020-01-26
827     2020-01-26
828     2020-01-26
829     2020-01-26
830     2020-01-26
831     2020-01-26
832     2020-01-26
833     2020-01-26
834     2020-01-26
835     2020-01-26
836     2020-01-26
837     2020-01-26
838     2020-01-26
839     2020-01-26
840     2020-01-26
841     2020-01-26
842     2020-01-26
843     2020-01-26
844     2020-01-26
845     2020-01-26
846     2020-01-26
847     2020-01-26
848     2020-01-26
849     2020-01-26
850     2020-01-26
851     2020-01-26
852     2020-01-26
853     2020-01-26
854     2020-01-26
855     2020-01-26
856     2020-01-26
857     2020-01-26
858     2020-01-26
859     2020-01-26
860     2020-01-26
861     2020-01-26
862     2020-01-26
863     2020-01-26
864     2020-01-26
865     2020-01-26
866     2020-01-26
867     2020-01-26
868     2020-01-26
869     2020-01-26
870     2020-01-26
871     2020-01-26
872     2020-01-26
873     2020-01-26
874     2020-01-26
875     2020-01-26
876     2020-01-26
877     2020-01-26
878     2020-01-26
879     2020-01-26
880     2020-01-26
881     2020-01-26
882     2020-01-26
883     2020-01-26
884     2020-01-26
885     2020-01-26
886     2020-01-26
887     2020-01-26
888     2020-01-26
889     2020-01-26
890     2020-01-26
891     2020-01-26
892     2020-01-26
893     2020-01-26
894     2020-01-26
895     2020-01-26
896     2020-01-26
897     2020-01-26
898     2020-01-26
899     2020-01-26
900     2020-01-26
901     2020-01-26
902     2020-01-26
903     2020-01-26
904     2020-01-26
905     2020-01-26
906     2020-01-26
907     2020-01-26
908     2020-01-26
909     2020-01-26
910     2020-01-26
911     2020-01-26
912     2020-01-26
913     2020-01-26
914     2020-01-26
915     2020-01-26
916     2020-01-26
917     2020-01-26
918     2020-01-26
919     2020-01-26
920     2020-01-26
921     2020-01-26
922     2020-01-26
923     2020-01-26
924     2020-01-26
925     2020-01-26
926     2020-01-26
927     2020-01-26
928     2020-01-26
929     2020-01-26
930     2020-01-26
931     2020-01-26
932     2020-01-26
933     2020-01-26
934     2020-01-26
935     2020-01-27
936     2020-01-27
937     2020-01-27
938     2020-01-27
939     2020-01-27
940     2020-01-27
941     2020-01-27
942     2020-01-27
943     2020-01-27
944     2020-01-27
945     2020-01-27
946     2020-01-27
947     2020-01-27
948     2020-01-27
949     2020-01-27
950     2020-01-27
951     2020-01-27
952     2020-01-27
953     2020-01-27
954     2020-01-27
955     2020-01-27
956     2020-01-27
957     2020-01-27
958     2020-01-27
959     2020-01-27
960     2020-01-27
961     2020-01-27
962     2020-01-27
963     2020-01-27
964     2020-01-27
965     2020-01-27
966     2020-01-27
967     2020-01-27
968     2020-01-27
969     2020-01-27
970     2020-01-27
971     2020-01-27
972     2020-01-27
973     2020-01-27
974     2020-01-27
975     2020-01-27
976     2020-01-27
977     2020-01-27
978     2020-01-27
979     2020-01-27
980     2020-01-27
981     2020-01-27
982     2020-01-27
983     2020-01-27
984     2020-01-27
985     2020-01-27
986     2020-01-27
987     2020-01-27
988     2020-01-27
989     2020-01-27
990     2020-01-27
991     2020-01-27
992     2020-01-27
993     2020-01-27
994     2020-01-27
995     2020-01-27
996     2020-01-27
997     2020-01-27
998     2020-01-27
999     2020-01-27
1000    2020-01-27
1001    2020-01-27
1002    2020-01-27
1003    2020-01-27
1004    2020-01-27
1005    2020-01-27
1006    2020-01-27
1007    2020-01-27
1008    2020-01-27
1009    2020-01-27
1010    2020-01-27
1011    2020-01-27
1012    2020-01-27
1013    2020-01-27
1014    2020-01-27
1015    2020-01-27
1016    2020-01-27
1017    2020-01-27
1018    2020-01-27
1019    2020-01-27
1020    2020-01-27
1021    2020-01-27
1022    2020-01-27
1023    2020-01-27
1024    2020-01-27
1025    2020-01-27
1026    2020-01-27
1027    2020-01-27
1028    2020-01-27
1029    2020-01-27
1030    2020-01-27
1031    2020-01-27
1032    2020-01-27
1033    2020-01-27
1034    2020-01-27
1035    2020-01-27
1036    2020-01-27
1037    2020-01-27
1038    2020-01-27
1039    2020-01-27
1040    2020-01-27
1041    2020-01-27
1042    2020-01-27
1043    2020-01-27
1044    2020-01-27
1045    2020-01-27
1046    2020-01-27
1047    2020-01-27
1048    2020-01-27
1049    2020-01-27
1050    2020-01-27
1051    2020-01-27

## 8. Create derived columns

The derived rates convert counts into comparable proportions:

- `fatality_rate` is the share of confirmed cases recorded as deaths.
- `recovery_rate` is the share of confirmed cases recorded as recovered.
- `active_rate` is the share of confirmed cases still active.
- `test_positivity_rate` is confirmed cases divided by tests conducted.

Zero denominators are replaced with missing values before division to avoid infinite or misleading rates. Vaccination coverage is grouped as low (below 40), medium (40–69), and high (70 or above) for a simple comparison of average active rates.

In [36]:
rate_analysis = covid19_statistics_copy.dropna(
    subset=["active"]
).copy()

confirmed_denominator = rate_analysis["confirmed"].mask(
    rate_analysis["confirmed"].eq(0)
)

tests_denominator = rate_analysis["tests_conducted"].mask(
    rate_analysis["tests_conducted"].eq(0)
)

rate_analysis["fatality_rate"] = (
    rate_analysis["deaths"] / confirmed_denominator
)

rate_analysis["recovery_rate"] = (
    rate_analysis["recovered"] / confirmed_denominator
)

rate_analysis["active_rate"] = (
    rate_analysis["active"] / confirmed_denominator
)

rate_analysis["test_positivity_rate"] = (
    rate_analysis["confirmed"] / tests_denominator
)

rate_columns = [
    "fatality_rate",
    "recovery_rate",
    "active_rate",
    "test_positivity_rate"
]

display_columns = [
    "country",
    "date",
    "confirmed",
    "deaths",
    "recovered",
    "active"
] + rate_columns

(
    rate_analysis[display_columns]
    .sort_values(["country", "date"])
    .reset_index(drop=True)
    .style.format({
        column: "{:.2%}" for column in rate_columns
    })
)

In [37]:
vaccination_group = rate_analysis.copy()

vaccination_group["vaccination_label"] = (
    vaccination_group["vaccination_rate_pct"].apply(
        lambda vaccination: (
            "low" if vaccination <= 39
            else "medium" if vaccination <= 69
            else "high"
        )
    )
)

vaccination_output = vaccination_group[
    ["country", "date", "vaccination_rate_pct", "vaccination_label"]
].sort_values(["country", "date"]).reset_index(drop=True)

vaccination_output

            country       date  vaccination_rate_pct vaccination_label
0            Brazil 2021-01-03                    59            medium
1            Brazil 2021-01-13                    39               low
2            Brazil 2021-01-23                    96              high
3            Brazil 2021-01-24                    40            medium
4            Brazil 2021-01-25                    17               low
5            Brazil 2021-01-27                    25               low
6            Brazil 2021-02-03                    42            medium
7            Brazil 2021-02-09                    65            medium
8            Brazil 2021-02-16                    84              high
9            Brazil 2021-02-17                    82              high
10           Brazil 2021-02-18                    71              high
11           Brazil 2021-02-19                    42            medium
12           Brazil 2021-02-22                    65            medium
13           Brazil 2021-03-01                    76              high
14           Brazil 2021-03-02                    52            medium
15           Brazil 2021-03-03                    65            medium
16           Brazil 2021-03-17                    86              high
17           Brazil 2021-03-19                    21               low
18           Brazil 2021-03-26                    38               low
19           Brazil 2021-03-30                    10               low
20           Brazil 2021-03-31                    58            medium
21           Brazil 2021-04-02                    68            medium
22           Brazil 2021-04-05                    26               low
23           Brazil 2021-04-10                    46            medium
24           Brazil 2021-04-16                    52            medium
25           Brazil 2021-04-23                    84              high
26           Brazil 2021-04-25                    37               low
27           Brazil 2021-05-02                    41            medium
28           Brazil 2021-05-06                    83              high
29           Brazil 2021-05-08                    11               low
30           Brazil 2021-05-21                    54            medium
31           Brazil 2021-06-27                    59            medium
32           Brazil 2021-06-29                   100              high
33           Brazil 2021-07-03                    89              high
34           Brazil 2021-07-11                    57            medium
35           Brazil 2021-07-12                    59            medium
36           Brazil 2021-07-17                    76              high
37            India 2021-01-10                    31               low
38            India 2021-01-18                    91              high
39            India 2021-01-19                    98              high
40            India 2021-01-22                    86              high
41            India 2021-01-31                    99              high
42            India 2021-02-08                    82              high
43            India 2021-02-11                    15               low
44            India 2021-02-20                    85              high
45            India 2021-02-27                    37               low
46            India 2021-03-07                    86              high
47            India 2021-03-09                    53            medium
48            India 2021-03-12                    20               low
49            India 2021-03-27                    25               low
50            India 2021-04-07                    75              high
51            India 2021-04-11                    54            medium
52            India 2021-04-20                    93              high
53            India 2021-04-24                    70              high
54            India 2021-04-27                    95              high
55            India 2021-05-01                    36               low
56            India 2021-05-04                    39               low
57            India 2021-05-05                    82              high
58            India 2021-05-12                    84              high
59            India 2021-05-13                    90              high
60            India 2021-05-14                    68            medium
61            India 2021-05-15                    16               low
62            India 2021-06-05                   100              high
63            India 2021-06-08                    79              high
64            India 2021-06-20                    90              high
65            India 2021-07-06                    62            medium
66            India 2021-07-08                    73              high
67            India 2021-07-10                    53            medium
68            India 2021-07-20                    25               low
69            Japan 2021-01-04                    35               low
70            Japan 2021-01-08                    95              high
71            Japan 2021-01-09                    72              high
72            Japan 2021-01-15                    46            medium
73            Japan 2021-01-16                    32               low
74            Japan 2021-01-17                    56            medium
75            Japan 2021-01-20                    92              high
76            Japan 2021-01-21                    77              high
77            Japan 2021-01-26                    83              high
78            Japan 2021-02-05                    38               low
79            Japan 2021-02-06                    52            medium
80            Japan 2021-02-07                    84              high
81            Japan 2021-02-13                    81              high
82            Japan 2021-02-14                    50            medium
83            Japan 2021-03-05                    13               low
84            Japan 2021-03-08                    77              high
85            Japan 2021-03-14                    77              high
86            Japan 2021-03-16                    17               low
87            Japan 2021-03-20                    41            medium
88            Japan 2021-04-03                    91              high
89            Japan 2021-04-21                    37               low
90            Japan 2021-04-22                    85              high
91            Japan 2021-04-28                    62            medium
92            Japan 2021-04-30                    10               low
93            Japan 2021-05-11                    55            medium
94            Japan 2021-05-19                    53            medium
95            Japan 2021-05-23                    32               low
96            Japan 2021-05-24                    22               low
97            Japan 2021-05-25                    68            medium
98            Japan 2021-05-29                    66            medium
99            Japan 2021-06-10                    36               low
100           Japan 2021-06-15                    71              high
101           Japan 2021-06-16                    97              high
102           Japan 2021-06-17                    20               low
103           Japan 2021-06-19                    59            medium
104           Japan 2021-06-24                    40            medium
105           Japan 2021-07-05                    43            medium
106           Japan 2021-07-16                    23               low
107           Japan 2021-07-18                    47            medium
108              US 2021-01-02                    99              high
109              US 2021-01-07                    33               low
110              US 2021-01-14                    37               low
111              US 2021-01-28                    91              high
112              US 2021-01-29                    59            medium
113              US 2021-02-10                    94              high
114              US 2021-02-12                    60            medium
115              US 2021-02-21                    22               low
116              US 2021-02-23                    97              high
117              US 2021-02-24                    64            medium
118              US 2021-02-25                    90              high
119              US 2021-02-28                    32               low
120              US 2021-03-06                    71              high
121              US 2021-03-13                    55            medium
122              US 2021-03-18                    60            medium
123              US 2021-03-22                    36               low
124              US 2021-03-23                    21               low
125              US 2021-03-29                    94              high
126              US 2021-04-06                    76              high
127              US 2021-04-12                    51            medium
128              US 2021-04-29                    55            medium
129              US 2021-05-03                    83              high
130              US 2021-05-07                    43            medium
131              US 2021-05-10                    99              high
132              US 2021-05-17                    52            medium
133              US 2021-05-18                    11               low
134              US 2021-05-26                    99              high
135              US 2021-05-28                    92              high
136              US 2021-05-30                    71              high
137              US 2021-05-31                    11               low
138              US 2021-06-01                    58            medium
139              US 2021-06-02                    80              high
140              US 2021-06-03                    19               low
141              US 2021-06-07                    54            medium
142              US 2021-06-09                    83              high
143              US 2021-06-26                    71              high
144              US 2021-06-28                    74              high
145              US 2021-07-04                    46            medium
146              US 2021-07-07                    58            medium
147              US 2021-07-09                    94              high
148              US 2021-07-15                    49            medium
149              US 2021-07-19                    71              high
150  United Kingdom 2021-01-05                    73              high
151  United Kingdom 2021-01-06                    70              high
152  United Kingdom 2021-01-11                    73              high
153  United Kingdom 2021-01-12                    93              high
154  United Kingdom 2021-01-30                    27               low
155  United Kingdom 2021-02-02                    82              high
156  United Kingdom 2021-02-04                    13               low
157  United Kingdom 2021-02-15                    45            medium
158  United Kingdom 2021-03-04                    54            medium
159  United Kingdom 2021-03-10                    92              high
160  United Kingdom 2021-03-11                    27               low
161  United Kingdom 2021-03-15                    41            medium
162  United Kingdom 2021-03-21                    94              high
163  United Kingdom 2021-03-24                    81              high
164  United Kingdom 2021-03-25                    88              high
165  United Kingdom 2021-03-28                    86              high
166  United Kingdom 2021-04-01                    40            medium
167  United Kingdom 2021-04-09                    50            medium
168  United Kingdom 2021-04-13                    26               low
169  United Kingdom 2021-04-14                    96              high
170  United Kingdom 2021-04-15                    13               low
171  United Kingdom 2021-04-17                    95              high
172  United Kingdom 2021-04-18                    48            medium
173  United Kingdom 2021-04-19                    54            medium
174  United Kingdom 2021-04-26                    76              high
175  United Kingdom 2021-05-09                    50            medium
176  United Kingdom 2021-05-16                    94              high
177  United Kingdom 2021-05-20                    19               low
178  United Kingdom 2021-05-22                    24               low
179  United Kingdom 2021-05-27                    15               low
180  United Kingdom 2021-06-04                    53            medium
181  United Kingdom 2021-06-12                    87              high
182  United Kingdom 2021-06-13                    15               low
183  United Kingdom 2021-06-14                    31               low
184  United Kingdom 2021-06-18                    60            medium
185  United Kingdom 2021-06-22                    56            medium
186  United Kingdom 2021-06-23                    30               low
187  United Kingdom 2021-07-01                    54            medium
188  United Kingdom 2021-07-02                    60            medium
189  United Kingdom 2021-07-13                    11               low

## 9. Aggregations

Country-level summaries combine confirmed cases, deaths, average fatality rates, and average vaccination coverage in the teacher data. A second aggregation compares average active rates across vaccination groups. These tables support the business questions while preserving the number of records contributing to each group.

In [38]:
aggregation_data = rate_analysis.copy()
teacher_csv_summary = (
    aggregation_data.groupby("country", as_index=False)
    .agg(
        total_confirmed=("confirmed", "sum"),
        total_deaths=("deaths", "sum"),
        average_fatality_rate=("fatality_rate", "mean"),
        average_vaccination_rate=("vaccination_rate_pct", "mean")
    )
    .sort_values("total_confirmed", ascending=False)
)

teacher_csv_summary.style.format({
    "total_confirmed": "{:,.0f}",
    "total_deaths": "{:,.0f}",
    "average_fatality_rate": "{:.2%}",
    "average_vaccination_rate": "{:.1f}%"
})

In [39]:
vaccination_data = vaccination_group.copy()
vaccination_summary = (
    vaccination_data.dropna(subset=["active_rate"])
    .groupby("vaccination_label", as_index=False)
    .agg(
        average_active_rate=("active_rate", "mean"),
        number_of_records=("record_id", "count")
    )
    .sort_values("average_active_rate", ascending=False)
)

vaccination_summary.style.format({
    "average_active_rate": "{:.2%}"
})

## 10. Reconciliation between sources

I build one country-level summary per source, compare the sets of standardized country names, and outer-join the totals. All five teacher countries match Kaggle labels after cleaning, while Kaggle includes 182 additional countries. Difference columns make the numerical gaps explicit.

The amounts are not expected to agree: Kaggle ends on July 27, 2020 and uses the last cumulative total per country, whereas the teacher data contains selected 2021 records whose values are summed. Therefore, the reconciliation verifies naming and coverage more reliably than numerical equality; the differences must not be interpreted as errors in either source without matching dates and aggregation definitions.

In [40]:
kaggle_csv_summary = full_grouped_copy.copy().sort_values(
    ["country", "date"]
)
confirmed_denominator = kaggle_csv_summary["confirmed"].mask(
    kaggle_csv_summary["confirmed"].eq(0)
)

kaggle_csv_summary["fatality_rate"] = (
    kaggle_csv_summary["deaths"] / confirmed_denominator
)
kaggle_csv_summary = (
    kaggle_csv_summary.groupby("country", as_index=False)
    .agg(
        total_confirmed=("confirmed", "last"),
        total_deaths=("deaths", "last"),
        average_fatality_rate=("fatality_rate", "mean")
    )
    .sort_values("total_confirmed", ascending=False)
)

kaggle_csv_summary.style.format({
    "total_confirmed": "{:,.0f}",
    "total_deaths": "{:,.0f}",
    "average_fatality_rate": "{:.2%}"
})

In [41]:
primary_key = "country"

teacher_csv_keys = set(teacher_csv_summary[primary_key])
kaggle_csv_keys = set(kaggle_csv_summary[primary_key])

missing_in_kaggle_csv = teacher_csv_summary.loc[
    ~teacher_csv_summary[primary_key].isin(kaggle_csv_keys)
]

missing_in_teacher_csv = kaggle_csv_summary.loc[
    ~kaggle_csv_summary[primary_key].isin(teacher_csv_keys)
]

print("Teacher records missing from Kaggle:")
display(missing_in_kaggle_csv)

print("Kaggle records missing from teacher data:")
display(missing_in_teacher_csv)

Teacher records missing from Kaggle:

Empty DataFrame
Columns: [country, total_confirmed, total_deaths, average_fatality_rate, average_vaccination_rate]
Index: []

Kaggle records missing from teacher data:

,country,total_confirmed,total_deaths,average_fatality_rate
138,Russia,816680,13334,0.007991
154,South Africa,452529,7067,0.014058
111,Mexico,395489,44022,0.081252
132,Peru,389717,18418,0.027028
35,Chile,347923,9187,0.011049
81,Iran,293606,15912,0.068408
128,Pakistan,274289,5842,0.016233
157,Spain,272421,28432,0.081018
145,Saudi Arabia,268934,2760,0.007006
37,Colombia,257101,8777,0.030193
85,Italy,246286,35112,0.106287
172,Turkey,227019,5630,0.023601
13,Bangladesh,226225,2965,0.029337
61,France,220352,30212,0.102330
65,Germany,207112,9125,0.026923
6,Argentina,167416,3059,0.032796
32,Canada,116458,8944,0.044554
82,Iraq,112585,4458,0.046521
136,Qatar,109597,165,0.000981
80,Indonesia,100303,4838,0.061553
52,Egypt,92482,4652,0.042575
36,China,86783,4656,0.045179
89,Kazakhstan,84648,585,0.006497
133,Philippines,82040,1945,0.108051
51,Ecuador,81161,5532,0.057832
161,Sweden,79395,5700,0.065770
127,Oman,77058,393,0.003654
20,Bolivia,71181,2647,0.038363
15,Belarus,67251,538,0.005588
175,Ukraine,67096,1636,0.035336
16,Belgium,66428,9822,0.104006
92,Kuwait,64379,438,0.004862
50,Dominican Republic,64156,1083,0.029269
84,Israel,63985,474,0.009720
129,Panama,61442,1322,0.024336
176,United Arab Emirates,59177,345,0.005237
120,Netherlands,53413,6160,0.099179
150,Singapore,50838,27,0.000919
135,Portugal,50299,1719,0.031390
137,Romania,45902,2206,0.046586
70,Guatemala,45309,1761,0.038137
134,Poland,43402,1676,0.036355
124,Nigeria,41180,860,0.021843
76,Honduras,39741,1166,0.043461
12,Bahrain,39482,141,0.002916
7,Armenia,37390,711,0.012337
0,Afghanistan,36263,1269,0.021596
162,Switzerland,34477,1978,0.045769
66,Ghana,33624,168,0.009827
93,Kyrgyzstan,33296,1301,0.012251
10,Azerbaijan,30446,423,0.013219
2,Algeria,27973,1163,0.074630
83,Ireland,25892,1764,0.048773
147,Serbia,24141,543,0.018255
112,Moldova,23154,748,0.026954
179,Uzbekistan,21209,121,0.004248
116,Morocco,20887,316,0.036200
9,Austria,20558,713,0.028027
119,Nepal,18752,48,0.001266
90,Kenya,17975,285,0.030067
31,Cameroon,17110,391,0.024667
180,Venezuela,15988,146,0.017500
41,Costa Rica,15841,115,0.006670
42,Cote d'Ivoire,15655,96,0.008081
46,Czechia,15516,373,0.023545
8,Australia,15303,167,0.010595
53,El Salvador,15035,408,0.024451
58,Ethiopia,14547,228,0.016375
155,South Korea,14203,300,0.016003
47,Denmark,13761,613,0.037910
159,Sudan,11424,720,0.142135
182,West Bank and Gaza,10621,78,0.004914
25,Bulgaria,10621,347,0.043175
21,Bosnia and Herzegovina,10498,294,0.037826
125,North Macedonia,10213,466,0.038944
146,Senegal,9764,194,0.010014
103,Madagascar,9690,91,0.004293
126,Norway,9132,255,0.020609
105,Malaysia,8904,124,0.010396
40,Congo (Kinshasa),8844,208,0.040455
91,Kosovo,7413,185,0.023412
60,Finland,7398,329,0.026731
74,Haiti,7340,158,0.035925
165,Tajikistan,7235,60,0.013040
62,Gabon,7189,49,0.025506
71,Guinea,7055,45,0.004444
102,Luxembourg,6321,112,0.019816
109,Mauritania,6208,156,0.068619
48,Djibouti,5059,58,0.005860
43,Croatia,4881,139,0.027133
1,Albania,4880,144,0.033793
33,Central African Republic,4599,59,0.004066
185,Zambia,4552,140,0.018947
131,Paraguay,4548,43,0.020004
77,Hungary,4448,596,0.101550
67,Greece,4227,202,0.044228
96,Lebanon,3882,51,0.021944
104,Malawi,3664,99,0.042935
122,Nicaragua,3439,108,0.115749
106,Maldives,3369,15,0.002455
167,Thailand,3297,58,0.012808
39,Congo (Brazzaville),3200,54,0.033326
153,Somalia,3196,93,0.031739
54,Equatorial Guinea,3071,51,0.008893
115,Montenegro,2893,45,0.019992
99,Libya,2827,64,0.030606
158,Sri Lanka,2805,11,0.007511
186,Zimbabwe,2704,36,0.076603
44,Cuba,2532,87,0.035661
107,Mali,2513,124,0.058381
29,Cabo Verde,2328,22,0.036394
57,Eswatini,2316,34,0.010329
156,South Sudan,2305,46,0.010343
151,Slovakia,2181,28,0.012151
152,Slovenia,2087,116,0.051765
56,Estonia,2034,69,0.024701
101,Lithuania,2019,80,0.029062
72,Guinea-Bissau,1954,26,0.007030
139,Rwanda,1879,5,0.001347
78,Iceland,1854,10,0.004545
118,Namibia,1843,8,0.000388
149,Sierra Leone,1783,66,0.037798
18,Benin,1770,35,0.014850
117,Mozambique,1701,11,0.003216
184,Yemen,1691,483,0.192907
121,New Zealand,1557,22,0.009625
160,Suriname,1483,24,0.050477
171,Tunisia,1455,50,0.036223
95,Latvia,1219,31,0.015776
178,Uruguay,1202,35,0.022069
88,Jordan,1176,11,0.010632
98,Liberia,1167,72,0.071818
64,Georgia,1137,16,0.011013
123,Niger,1132,69,0.055873
174,Uganda,1128,2,0.000042
26,Burkina Faso,1100,53,0.053822
45,Cyprus,1060,19,0.017034
4,Angola,950,41,0.065524
34,Chad,922,75,0.060647
3,Andorra,907,52,0.047119
169,Togo,874,18,0.032445
144,Sao Tome and Principe,865,14,0.018964
86,Jamaica,853,10,0.022811
22,Botswana,739,2,0.041273
108,Malta,701,9,0.008904
143,San Marino,699,42,0.069415
163,Syria,674,40,0.056124
166,Tanzania,509,21,0.037432
97,Lesotho,505,12,0.003679
164,Taiwan*,462,7,0.014991
181,Vietnam,431,0,0.000000
73,Guyana,389,20,0.114272
11,Bahamas,382,11,0.099906
28,Burundi,378,1,0.037758
38,Comoros,354,7,0.030741
27,Burma,350,6,0.031982
110,Mauritius,344,10,0.029721
63,Gambia,326,8,0.084186
114,Mongolia,289,0,0.000000
55,Eritrea,265,0,0.000000
30,Cambodia,226,0,0.000000
170,Trinidad and Tobago,148,8,0.058776
24,Brunei,141,3,0.011451
113,Monaco,116,4,0.028735
148,Seychelles,114,0,0.000000
14,Barbados,110,7,0.061621
19,Bhutan,99,0,0.000000
5,Antigua and Barbuda,86,3,0.077187
100,Liechtenstein,86,1,0.009686
130,Papua New Guinea,62,0,0.000690
142,Saint Vincent and the Grenadines,52,0,0.000000
17,Belize,48,2,0.085160
59,Fiji,27,0,0.000000
141,Saint Lucia,24,0,0.000000
168,Timor-Leste,24,0,0.000000
69,Grenada,23,0,0.000000
94,Laos,20,0,0.000000
49,Dominica,18,0,0.000000
140,Saint Kitts and Nevis,17,0,0.000000
68,Greenland,14,0,0.000000
75,Holy See,12,0,0.000000
183,Western Sahara,10,1,0.057895

In [42]:
teacher_amounts = teacher_csv_summary[
    ["country", "total_confirmed", "total_deaths"]
].rename(
    columns={
        "total_confirmed": "teacher_total_confirmed",
        "total_deaths": "teacher_total_deaths"
    }
)

kaggle_amounts = kaggle_csv_summary[
    ["country", "total_confirmed", "total_deaths"]
].rename(
    columns={
        "total_confirmed": "kaggle_total_confirmed",
        "total_deaths": "kaggle_total_deaths"
    }
)

country_reconciliation = teacher_amounts.merge(
    kaggle_amounts,
    on="country",
    how="outer"
).fillna(0)

country_reconciliation["confirmed_difference"] = (
    country_reconciliation["kaggle_total_confirmed"]
    - country_reconciliation["teacher_total_confirmed"]
)

country_reconciliation["deaths_difference"] = (
    country_reconciliation["kaggle_total_deaths"]
    - country_reconciliation["teacher_total_deaths"]
)

country_reconciliation

,country,teacher_total_confirmed,teacher_total_deaths,kaggle_total_confirmed,kaggle_total_deaths,confirmed_difference,deaths_difference
0,Afghanistan,0.0,0.0,36263,1269,36263.0,1269.0
1,Albania,0.0,0.0,4880,144,4880.0,144.0
2,Algeria,0.0,0.0,27973,1163,27973.0,1163.0
3,Andorra,0.0,0.0,907,52,907.0,52.0
4,Angola,0.0,0.0,950,41,950.0,41.0
5,Antigua and Barbuda,0.0,0.0,86,3,86.0,3.0
6,Argentina,0.0,0.0,167416,3059,167416.0,3059.0
7,Armenia,0.0,0.0,37390,711,37390.0,711.0
8,Australia,0.0,0.0,15303,167,15303.0,167.0
9,Austria,0.0,0.0,20558,713,20558.0,713.0
10,Azerbaijan,0.0,0.0,30446,423,30446.0,423.0
11,Bahamas,0.0,0.0,382,11,382.0,11.0
12,Bahrain,0.0,0.0,39482,141,39482.0,141.0
13,Bangladesh,0.0,0.0,226225,2965,226225.0,2965.0
14,Barbados,0.0,0.0,110,7,110.0,7.0
15,Belarus,0.0,0.0,67251,538,67251.0,538.0
16,Belgium,0.0,0.0,66428,9822,66428.0,9822.0
17,Belize,0.0,0.0,48,2,48.0,2.0
18,Benin,0.0,0.0,1770,35,1770.0,35.0
19,Bhutan,0.0,0.0,99,0,99.0,0.0
20,Bolivia,0.0,0.0,71181,2647,71181.0,2647.0
21,Bosnia and Herzegovina,0.0,0.0,10498,294,10498.0,294.0
22,Botswana,0.0,0.0,739,2,739.0,2.0
23,Brazil,7073638.0,103779.0,2442375,87618,-4631263.0,-16161.0
24,Brunei,0.0,0.0,141,3,141.0,3.0
25,Bulgaria,0.0,0.0,10621,347,10621.0,347.0
26,Burkina Faso,0.0,0.0,1100,53,1100.0,53.0
27,Burma,0.0,0.0,350,6,350.0,6.0
28,Burundi,0.0,0.0,378,1,378.0,1.0
29,Cabo Verde,0.0,0.0,2328,22,2328.0,22.0
30,Cambodia,0.0,0.0,226,0,226.0,0.0
31,Cameroon,0.0,0.0,17110,391,17110.0,391.0
32,Canada,0.0,0.0,116458,8944,116458.0,8944.0
33,Central African Republic,0.0,0.0,4599,59,4599.0,59.0
34,Chad,0.0,0.0,922,75,922.0,75.0
35,Chile,0.0,0.0,347923,9187,347923.0,9187.0
36,China,0.0,0.0,86783,4656,86783.0,4656.0
37,Colombia,0.0,0.0,257101,8777,257101.0,8777.0
38,Comoros,0.0,0.0,354,7,354.0,7.0
39,Congo (Brazzaville),0.0,0.0,3200,54,3200.0,54.0
40,Congo (Kinshasa),0.0,0.0,8844,208,8844.0,208.0
41,Costa Rica,0.0,0.0,15841,115,15841.0,115.0
42,Cote d'Ivoire,0.0,0.0,15655,96,15655.0,96.0
43,Croatia,0.0,0.0,4881,139,4881.0,139.0
44,Cuba,0.0,0.0,2532,87,2532.0,87.0
45,Cyprus,0.0,0.0,1060,19,1060.0,19.0
46,Czechia,0.0,0.0,15516,373,15516.0,373.0
47,Denmark,0.0,0.0,13761,613,13761.0,613.0
48,Djibouti,0.0,0.0,5059,58,5059.0,58.0
49,Dominica,0.0,0.0,18,0,18.0,0.0
50,Dominican Republic,0.0,0.0,64156,1083,64156.0,1083.0
51,Ecuador,0.0,0.0,81161,5532,81161.0,5532.0
52,Egypt,0.0,0.0,92482,4652,92482.0,4652.0
53,El Salvador,0.0,0.0,15035,408,15035.0,408.0
54,Equatorial Guinea,0.0,0.0,3071,51,3071.0,51.0
55,Eritrea,0.0,0.0,265,0,265.0,0.0
56,Estonia,0.0,0.0,2034,69,2034.0,69.0
57,Eswatini,0.0,0.0,2316,34,2316.0,34.0
58,Ethiopia,0.0,0.0,14547,228,14547.0,228.0
59,Fiji,0.0,0.0,27,0,27.0,0.0
60,Finland,0.0,0.0,7398,329,7398.0,329.0
61,France,0.0,0.0,220352,30212,220352.0,30212.0
62,Gabon,0.0,0.0,7189,49,7189.0,49.0
63,Gambia,0.0,0.0,326,8,326.0,8.0
64,Georgia,0.0,0.0,1137,16,1137.0,16.0
65,Germany,0.0,0.0,207112,9125,207112.0,9125.0
66,Ghana,0.0,0.0,33624,168,33624.0,168.0
67,Greece,0.0,0.0,4227,202,4227.0,202.0
68,Greenland,0.0,0.0,14,0,14.0,0.0
69,Grenada,0.0,0.0,23,0,23.0,0.0
70,Guatemala,0.0,0.0,45309,1761,45309.0,1761.0
71,Guinea,0.0,0.0,7055,45,7055.0,45.0
72,Guinea-Bissau,0.0,0.0,1954,26,1954.0,26.0
73,Guyana,0.0,0.0,389,20,389.0,20.0
74,Haiti,0.0,0.0,7340,158,7340.0,158.0
75,Holy See,0.0,0.0,12,0,12.0,0.0
76,Honduras,0.0,0.0,39741,1166,39741.0,1166.0
77,Hungary,0.0,0.0,4448,596,4448.0,596.0
78,Iceland,0.0,0.0,1854,10,1854.0,10.0
79,India,8598659.0,124867.0,1480073,33408,-7118586.0,-91459.0
80,Indonesia,0.0,0.0,100303,4838,100303.0,4838.0
81,Iran,0.0,0.0,293606,15912,293606.0,15912.0
82,Iraq,0.0,0.0,112585,4458,112585.0,4458.0
83,Ireland,0.0,0.0,25892,1764,25892.0,1764.0
84,Israel,0.0,0.0,63985,474,63985.0,474.0
85,Italy,0.0,0.0,246286,35112,246286.0,35112.0
86,Jamaica,0.0,0.0,853,10,853.0,10.0
87,Japan,9918172.0,138028.0,31142,998,-9887030.0,-137030.0
88,Jordan,0.0,0.0,1176,11,1176.0,11.0
89,Kazakhstan,0.0,0.0,84648,585,84648.0,585.0
90,Kenya,0.0,0.0,17975,285,17975.0,285.0
91,Kosovo,0.0,0.0,7413,185,7413.0,185.0
92,Kuwait,0.0,0.0,64379,438,64379.0,438.0
93,Kyrgyzstan,0.0,0.0,33296,1301,33296.0,1301.0
94,Laos,0.0,0.0,20,0,20.0,0.0
95,Latvia,0.0,0.0,1219,31,1219.0,31.0
96,Lebanon,0.0,0.0,3882,51,3882.0,51.0
97,Lesotho,0.0,0.0,505,12,505.0,12.0
98,Liberia,0.0,0.0,1167,72,1167.0,72.0
99,Libya,0.0,0.0,2827,64,2827.0,64.0
100,Liechtenstein,0.0,0.0,86,1,86.0,1.0
101,Lithuania,0.0,0.0,2019,80,2019.0,80.0
102,Luxembourg,0.0,0.0,6321,112,6321.0,112.0
103,Madagascar,0.0,0.0,9690,91,9690.0,91.0
104,Malawi,0.0,0.0,3664,99,3664.0,99.0
105,Malaysia,0.0,0.0,8904,124,8904.0,124.0
106,Maldives,0.0,0.0,3369,15,3369.0,15.0
107,Mali,0.0,0.0,2513,124,2513.0,124.0
108,Malta,0.0,0.0,701,9,701.0,9.0
109,Mauritania,0.0,0.0,6208,156,6208.0,156.0
110,Mauritius,0.0,0.0,344,10,344.0,10.0
111,Mexico,0.0,0.0,395489,44022,395489.0,44022.0
112,Moldova,0.0,0.0,23154,748,23154.0,748.0
113,Monaco,0.0,0.0,116,4,116.0,4.0
114,Mongolia,0.0,0.0,289,0,289.0,0.0
115,Montenegro,0.0,0.0,2893,45,2893.0,45.0
116,Morocco,0.0,0.0,20887,316,20887.0,316.0
117,Mozambique,0.0,0.0,1701,11,1701.0,11.0
118,Namibia,0.0,0.0,1843,8,1843.0,8.0
119,Nepal,0.0,0.0,18752,48,18752.0,48.0
120,Netherlands,0.0,0.0,53413,6160,53413.0,6160.0
121,New Zealand,0.0,0.0,1557,22,1557.0,22.0
122,Nicaragua,0.0,0.0,3439,108,3439.0,108.0
123,Niger,0.0,0.0,1132,69,1132.0,69.0
124,Nigeria,0.0,0.0,41180,860,41180.0,860.0
125,North Macedonia,0.0,0.0,10213,466,10213.0,466.0
126,Norway,0.0,0.0,9132,255,9132.0,255.0
127,Oman,0.0,0.0,77058,393,77058.0,393.0
128,Pakistan,0.0,0.0,274289,5842,274289.0,5842.0
129,Panama,0.0,0.0,61442,1322,61442.0,1322.0
130,Papua New Guinea,0.0,0.0,62,0,62.0,0.0
131,Paraguay,0.0,0.0,4548,43,4548.0,43.0
132,Peru,0.0,0.0,389717,18418,389717.0,18418.0
133,Philippines,0.0,0.0,82040,1945,82040.0,1945.0
134,Poland,0.0,0.0,43402,1676,43402.0,1676.0
135,Portugal,0.0,0.0,50299,1719,50299.0,1719.0
136,Qatar,0.0,0.0,109597,165,109597.0,165.0
137,Romania,0.0,0.0,45902,2206,45902.0,2206.0
138,Russia,0.0,0.0,816680,13334,816680.0,13334.0
139,Rwanda,0.0,0.0,1879,5,1879.0,5.0
140,Saint Kitts and Nevis,0.0,0.0,17,0,17.0,0.0
141,Saint Lucia,0.0,0.0,24,0,24.0,0.0
142,Saint Vincent and the Grenadines,0.0,0.0,52,0,52.0,0.0
143,San Marino,0.0,0.0,699,42,699.0,42.0
144,Sao Tome and Principe,0.0,0.0,865,14,865.0,14.0
145,Saudi Arabia,0.0,0.0,268934,2760,268934.0,2760.0
146,Senegal,0.0,0.0,9764,194,9764.0,194.0
147,Serbia,0.0,0.0,24141,543,24141.0,543.0
148,Seychelles,0.0,0.0,114,0,114.0,0.0
149,Sierra Leone,0.0,0.0,1783,66,1783.0,66.0
150,Singapore,0.0,0.0,50838,27,50838.0,27.0
151,Slovakia,0.0,0.0,2181,28,2181.0,28.0
152,Slovenia,0.0,0.0,2087,116,2087.0,116.0
153,Somalia,0.0,0.0,3196,93,3196.0,93.0
154,South Africa,0.0,0.0,452529,7067,452529.0,7067.0
155,South Korea,0.0,0.0,14203,300,14203.0,300.0
156,South Sudan,0.0,0.0,2305,46,2305.0,46.0
157,Spain,0.0,0.0,272421,28432,272421.0,28432.0
158,Sri Lanka,0.0,0.0,2805,11,2805.0,11.0
159,Sudan,0.0,0.0,11424,720,11424.0,720.0
160,Suriname,0.0,0.0,1483,24,1483.0,24.0
161,Sweden,0.0,0.0,79395,5700,79395.0,5700.0
162,Switzerland,0.0,0.0,34477,1978,34477.0,1978.0
163,Syria,0.0,0.0,674,40,674.0,40.0
164,Taiwan*,0.0,0.0,462,7,462.0,7.0
165,Tajikistan,0.0,0.0,7235,60,7235.0,60.0
166,Tanzania,0.0,0.0,509,21,509.0,21.0
167,Thailand,0.0,0.0,3297,58,3297.0,58.0
168,Timor-Leste,0.0,0.0,24,0,24.0,0.0
169,Togo,0.0,0.0,874,18,874.0,18.0
170,Trinidad and Tobago,0.0,0.0,148,8,148.0,8.0
171,Tunisia,0.0,0.0,1455,50,1455.0,50.0
172,Turkey,0.0,0.0,227019,5630,227019.0,5630.0
173,US,9774010.0,161964.0,4290259,148011,-5483751.0,-13953.0
174,Uganda,0.0,0.0,1128,2,1128.0,2.0
175,Ukraine,0.0,0.0,67096,1636,67096.0,1636.0
176,United Arab Emirates,0.0,0.0,59177,345,59177.0,345.0
177,United Kingdom,10574461.0,152570.0,301708,45844,-10272753.0,-106726.0
178,Uruguay,0.0,0.0,1202,35,1202.0,35.0
179,Uzbekistan,0.0,0.0,21209,121,21209.0,121.0
180,Venezuela,0.0,0.0,15988,146,15988.0,146.0
181,Vietnam,0.0,0.0,431,0,431.0,0.0
182,West Bank and Gaza,0.0,0.0,10621,78,10621.0,78.0
183,Western Sahara,0.0,0.0,10,1,10.0,1.0
184,Yemen,0.0,0.0,1691,483,1691.0,483.0
185,Zambia,0.0,0.0,4552,140,4552.0,140.0
186,Zimbabwe,0.0,0.0,2704,36,2704.0,36.0

## 11. Data quality validation report

The following helper functions express each rule as a consistent result record containing the check, column, expectation, observed value, failed-row count, severity, and pass/fail flag. High-severity failures block analysis, medium-severity failures require investigation, and low-severity failures are documented. Keeping failed checks visible is important because a failed rule is evidence about fitness for use, not a reason to hide the data.

In [43]:
def make_result(
    check_name,
    column,
    expectation,
    observed_value,
    failed_rows,
    severity,
    passed,
    sample_rows=None,
):
    return {
        "check_name": check_name,
        "column": column,
        "expectation": expectation,
        "observed_value": observed_value,
        "failed_rows": int(failed_rows),
        "severity": severity,
        "passed": bool(passed)
    }

In [44]:
validation_config = {
    # Columns that must exist
    "expected_columns": [
        "date",
        "country",
        "confirmed",
        "deaths",
        "recovered",
        "active",
        "new_cases",
        "new_deaths",
        "new_recovered",
        "who_region"
    ],

    # Columns where missing values are not permitted
    "not_null": [
        "date",
        "country",
        "confirmed",
        "deaths",
        "recovered",
        "active",
        "new_cases",
        "new_deaths",
        "new_recovered",
        "who_region"
    ],

    # Composite primary key
    "unique_keys": [
        ["country", "date"]
    ],

    # Date expectations
    "date_ranges": {
        "date": {
            "minimum": "2020-01-22",
            "maximum": "2020-07-27"
        }
    },

    # Numeric ranges
    "numeric_ranges": {
        "confirmed": {
            "min_value": 0,
            "max_value": None
        },
        "deaths": {
            "min_value": 0,
            "max_value": None
        },
        "recovered": {
            "min_value": 0,
            "max_value": None
        },
        "active": {
            "min_value": 0,
            "max_value": None
        },
        "new_cases": {
            "min_value": 0,
            "max_value": None
        },
        "new_deaths": {
            "min_value": 0,
            "max_value": None
        },
        "new_recovered": {
            "min_value": 0,
            "max_value": None
        }
    },

    # Accepted categorical values
    "accepted_values": {
        "who_region": [
            "Africa",
            "Americas",
            "Eastern Mediterranean",
            "Europe",
            "South-East Asia",
            "Western Pacific"
        ]
    },

}

In [45]:
def validate_schema(df, expected_columns, severity="high"):
    actual_columns = list(df.columns)
    missing_columns = sorted(set(expected_columns) - set(actual_columns))
    unexpected_columns = sorted(set(actual_columns) - set(expected_columns))
    passed = not missing_columns and not unexpected_columns

    return make_result(
        check_name="schema_columns",
        column="table",
        expectation=f"columns match expected schema: {expected_columns}",
        observed_value={"missing": missing_columns, "unexpected": unexpected_columns},
        failed_rows=len(missing_columns) + len(unexpected_columns),
        severity=severity,
        passed=passed,
    )


pd.DataFrame([validate_schema(full_grouped_copy, validation_config["expected_columns"])])

,check_name,column,expectation,observed_value,failed_rows,severity,passed
0,schema_columns,table,"columns match expected schema: ['date', 'count...","{'missing': [], 'unexpected': []}",0,high,True

In [46]:
def validate_not_null(df, column, severity="high"):
    failed_mask = df[column].isna()
    failed_indexes = df[failed_mask].index.tolist()

    return make_result(
        check_name="not_null",
        column=column,
        expectation="value is not null",
        observed_value=int(failed_mask.sum()),
        failed_rows=int(failed_mask.sum()),
        severity=severity,
        passed=failed_mask.sum() == 0,
        sample_rows=failed_indexes[:5],
    )


not_null_results = [validate_not_null(full_grouped_copy, column) for column in validation_config["not_null"]]

pd.DataFrame(not_null_results)

,check_name,column,expectation,observed_value,failed_rows,severity,passed
0,not_null,date,value is not null,0,0,high,True
1,not_null,country,value is not null,0,0,high,True
2,not_null,confirmed,value is not null,0,0,high,True
3,not_null,deaths,value is not null,0,0,high,True
4,not_null,recovered,value is not null,0,0,high,True
5,not_null,active,value is not null,0,0,high,True
6,not_null,new_cases,value is not null,0,0,high,True
7,not_null,new_deaths,value is not null,0,0,high,True
8,not_null,new_recovered,value is not null,0,0,high,True
9,not_null,who_region,value is not null,0,0,high,True

In [47]:
def validate_composite_key(df, columns):
    failed_mask = df.duplicated(
        subset=columns,
        keep=False
    )

    failed_count = int(failed_mask.sum())

    return make_result(
        check_name="unique_composite_key",
        column=", ".join(columns),
        expectation=f"{columns} combination is unique",
        observed_value=failed_count,
        failed_rows=failed_count,
        severity="high",
        passed=failed_count == 0,
        sample_rows=df.index[failed_mask].tolist()[:5]
    )

unique_result = validate_composite_key(
    full_grouped_copy,
    ["country", "date"]
)

pd.DataFrame([unique_result])

,check_name,column,expectation,observed_value,failed_rows,severity,passed
0,unique_composite_key,"country, date","['country', 'date'] combination is unique",0,0,high,True

In [48]:
def validate_accepted_values(df, column, accepted_values, severity="medium"):
    failed_mask = df[column].notna() & ~df[column].isin(accepted_values)
    failed_indexes = df[failed_mask].index.tolist()

    return make_result(
        check_name="accepted_values",
        column=column,
        expectation=f"value is one of {accepted_values}",
        observed_value=sorted(df.loc[failed_mask, column].dropna().unique().tolist()),
        failed_rows=int(failed_mask.sum()),
        severity=severity,
        passed=failed_mask.sum() == 0,
        sample_rows=failed_indexes[:5],
    )


accepted_value_results = [
    validate_accepted_values(full_grouped_copy, column, accepted_values)
    for column, accepted_values in validation_config["accepted_values"].items()
]

pd.DataFrame(accepted_value_results)

,check_name,column,expectation,observed_value,failed_rows,severity,passed
0,accepted_values,who_region,"value is one of ['Africa', 'Americas', 'Easter...",[],0,medium,True

In [49]:
def validate_numeric_range(df, column, min_value=None, max_value=None, severity="medium"):
    failed_mask = pd.Series(False, index=df.index)

    if min_value is not None:
        failed_mask = failed_mask | (df[column] < min_value)

    if max_value is not None:
        failed_mask = failed_mask | (df[column] > max_value)

    failed_mask = failed_mask & df[column].notna()
    failed_indexes = df[failed_mask].index.tolist()

    return make_result(
        check_name="numeric_range",
        column=column,
        expectation=f"value between {min_value} and {max_value}",
        observed_value=int(failed_mask.sum()),
        failed_rows=int(failed_mask.sum()),
        severity=severity,
        passed=failed_mask.sum() == 0,
        sample_rows=failed_indexes[:5],
    )


numeric_range_results = [
    validate_numeric_range(
        full_grouped_copy,
        column,
        min_value=rules.get("min_value"),
        max_value=rules.get("max_value"),
    )
    for column, rules in validation_config["numeric_ranges"].items()
]

pd.DataFrame(numeric_range_results)

,check_name,column,expectation,observed_value,failed_rows,severity,passed
0,numeric_range,confirmed,value between 0 and None,0,0,medium,True
1,numeric_range,deaths,value between 0 and None,0,0,medium,True
2,numeric_range,recovered,value between 0 and None,0,0,medium,True
3,numeric_range,active,value between 0 and None,2,2,medium,False
4,numeric_range,new_cases,value between 0 and None,0,0,medium,True
5,numeric_range,new_deaths,value between 0 and None,38,38,medium,False
6,numeric_range,new_recovered,value between 0 and None,77,77,medium,False

### Validation interpretation

The saved Kaggle validation outputs pass the schema, required-field, country-date uniqueness, and WHO-region checks. The cumulative columns `confirmed`, `deaths`, and `recovered` are non-negative. The numeric-range check still finds two negative `active` values, 38 negative `new_deaths` values, and 77 negative `new_recovered` values. Negative daily changes may represent historical corrections or reclassification, but that meaning is not documented here, so these failures should remain visible and be investigated before daily-change reporting.

## 12. Answers to the business questions

### 1. Which countries show the highest COVID-19 severity?

In the Kaggle snapshot, the largest confirmed totals are the US (4.29 million), Brazil (2.44 million), and India (1.48 million). The largest average fatality rates are shown for Yemen (19.29%), Sudan (14.21%), and Nicaragua (11.57%). These rate rankings require caution because countries with smaller case counts can produce unstable percentages and reporting practices differ. Within the five-country teacher sample, the US has the highest average fatality rate at 1.75%, while the United Kingdom has the largest summed confirmed count. The teacher totals are sums across selected 2021 records, so they are not directly comparable to Kaggle's last cumulative 2020 values.

### 2. Is higher testing or vaccination coverage associated with lower active-case rates?

The vaccination groups do not show a clear monotonic relationship. Average active rates are 14.74% for the low group (51 records), 13.38% for the medium group (63 records), and 14.70% for the high group (76 records). The high group is therefore almost identical to the low group rather than consistently lower. The current summaries also do not directly establish a relationship between testing coverage and active rate. These descriptive comparisons are not causal: country mix, date, outbreak stage, and the ten records excluded because of unreliable `active` values may confound the result.

## 13. Final conclusion

The main issues were inconsistent country and state labels, mixed and implausible date years, `-9999` active-case placeholders, ten case-balance failures, and negative daily changes in the Kaggle source. I standardized labels, corrected three date years using the surrounding daily sequence, and marked unreliable teacher `active` values as missing instead of inventing values.

The cleaned data is adequate for exploratory summaries with explicit limitations, but it is not yet reliable enough for an official cross-source business report. The sources cover different years and use totals with different meanings, and the negative Kaggle daily changes remain unresolved. Before production use, I would ask the providers to confirm the date corrections, define whether case fields are snapshots or cumulative totals, explain revision-driven negative daily values, document how tests and vaccination rates were measured, and provide a stable geographic identifier plus refresh and correction policies.