# Pandas Notebook 01: Introduction to pandas

Welcome! This notebook is a gentle first step into pandas. You already know Python basics, so we will build on that foundation and learn how pandas helps us work with tabular data.

## What you will learn

By the end of this notebook, you should be able to:

- explain what pandas is and why it is useful
- understand the difference between a `Series` and a `DataFrame`
- identify rows, columns, and indexes
- create pandas objects from Python data structures
- read a CSV file with pandas
- inspect a dataset with common pandas methods
- select columns, filter rows, and sort values

### Learning objectives

- feel comfortable reading simple pandas code
- practice the most common beginner operations on tabular data
- prepare for future notebooks that use real datasets

## 1. What pandas is and why it is useful

pandas is a Python library for working with structured data, especially tables.

It is useful because it makes common data tasks easier:

- loading data from files like CSVs
- exploring a dataset quickly
- selecting only the rows or columns you need
- filtering, sorting, and summarizing data

If Python lists and dictionaries are good for general programming, pandas is especially good for data analysis.

In [2]:
import pandas as pd

## 2. Series vs DataFrame

The two main pandas objects are:

- `Series`: a one-dimensional labeled collection of data
- `DataFrame`: a two-dimensional table with rows and columns

A good way to think about it:

- a `Series` is similar to one column in a table
- a `DataFrame` is the whole table

In [3]:
city_series = pd.Series(["Bogota", "Medellin", "Cali"], name="city")

In [6]:
city_series

0      Bogota
1    Medellin
2        Cali
Name: city, dtype: str

In [7]:
student_df = pd.DataFrame(
    {
        "name": ["Ana", "Luis", "Sara"],
        "score": [88, 92, 85],
        "passed": [True, True, True],
    }
)

print("Series:\n")
print(city_series)
print("\nDataFrame:\n")
student_df

Series:

0      Bogota
1    Medellin
2        Cali
Name: city, dtype: str

DataFrame:

   name  score  passed
0   Ana     88    True
1  Luis     92    True
2  Sara     85    True

In [20]:
student_df['name']

0     Ana
1    Luis
2    Sara
Name: name, dtype: str

## 3. Rows, columns, indexes

In a pandas `DataFrame`:

- each horizontal entry is a **row**
- each vertical entry is a **column**
- the **index** labels the rows

The index starts at `0` by default, but pandas can also use other values as row labels.

In [27]:
print("Row index:", list(student_df.index))
print("Columns:", list(student_df.columns))
print("\nRow with index 0:\n")
print(student_df.iloc[0,2])

Row index: [0, 1, 2]
Columns: ['name', 'score', 'passed']

Row with index 0:

True

In [30]:
list(student_df.columns)

['name', 'score', 'passed']

In [26]:
print(student_df.loc[0,'name'])

Ana

## 4. Creating Series and DataFrames from Python data structures

One reason pandas feels approachable is that you can create tables directly from data structures you already know, like lists and dictionaries.

In [31]:
# From a dictionary of lists
inventory_from_dict = pd.DataFrame(
    {
        "product": ["Notebook", "Mouse", "Keyboard"],
        "price": [4.5, 12.0, 25.0],
    }
)

# From a list of dictionaries
sales_from_records = pd.DataFrame(
    [
        {"month": "Jan", "sales": 120},
        {"month": "Feb", "sales": 150},
        {"month": "Mar", "sales": 165},
    ]
)

print("From a dictionary of lists:\n")
print(inventory_from_dict)
print("\nFrom a list of dictionaries:\n")
sales_from_records

From a dictionary of lists:

    product  price
0  Notebook    4.5
1     Mouse   12.0
2  Keyboard   25.0

From a list of dictionaries:

  month  sales
0   Jan    120
1   Feb    150
2   Mar    165

In [33]:
inventory_from_dict

    product  price
0  Notebook    4.5
1     Mouse   12.0
2  Keyboard   25.0

## 5. A small toy dataset

Before reading a file, it is helpful to practice with a tiny dataset created directly in the notebook. This keeps the focus on pandas concepts.

In [41]:
sales_df = pd.DataFrame(
    {
        "sale_id": [101, 102, 103, 104, 105, 106],
        "product": ["Laptop", "Mouse", "Desk", "Monitor", "Chair", "Keyboard"],
        "category": ["Electronics", "Electronics", "Furniture", "Electronics", "Furniture", "Electronics"],
        "price": [1200, 25.5, 300, 220, 150, 45],
        "quantity": [2, 10, 3, 4, 5, 7],
        "city": ["Bogota", "Cali", "Bogota", "Medellin", "Cali", "Bogota"],
        "in_stock": [True, True, False, True, True, True],
    }
)

sales_df

   sale_id   product     category   price  quantity      city  in_stock
0      101    Laptop  Electronics  1200.0         2    Bogota      True
1      102     Mouse  Electronics    25.5        10      Cali      True
2      103      Desk    Furniture   300.0         3    Bogota     False
3      104   Monitor  Electronics   220.0         4  Medellin      True
4      105     Chair    Furniture   150.0         5      Cali      True
5      106  Keyboard  Electronics    45.0         7    Bogota      True

## 6. Basic data inspection

When you first open a dataset, you usually want quick answers to questions like:

- What does it look like?
- How many rows and columns does it have?
- What are the column names?
- What type of data is inside each column?

pandas gives us several simple tools for this.

In [42]:
print("First 3 rows:\n")
print(sales_df.head(2))
print("\nLast 2 rows:\n")
sales_df.tail(2)

First 3 rows:

   sale_id product     category   price  quantity    city  in_stock
0      101  Laptop  Electronics  1200.0         2  Bogota      True
1      102   Mouse  Electronics    25.5        10    Cali      True

Last 2 rows:

   sale_id   product     category  price  quantity    city  in_stock
4      105     Chair    Furniture  150.0         5    Cali      True
5      106  Keyboard  Electronics   45.0         7  Bogota      True

In [43]:
print("Shape:", sales_df.shape)
print("Columns:", list(sales_df.columns))
print("Index:", list(sales_df.index))
print("\nData types:\n")
print(sales_df.dtypes)
print("\nInfo:\n")
sales_df.info()

Shape: (6, 7)
Columns: ['sale_id', 'product', 'category', 'price', 'quantity', 'city', 'in_stock']
Index: [0, 1, 2, 3, 4, 5]

Data types:

sale_id       int64
product         str
category        str
price       float64
quantity      int64
city            str
in_stock       bool
dtype: object

Info:

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sale_id   6 non-null      int64
 1   product   6 non-null      str
 2   category  6 non-null      str
 3   price     6 non-null      float64
 4   quantity  6 non-null      int64
 5   city      6 non-null      str
 6   in_stock  6 non-null      bool
dtypes: bool(1), float64(1), int64(2), str(3)
memory usage: 426.0 bytes

In [46]:
sales_df.describe(include="all")

,sale_id,product,category,price,quantity,city,in_stock
count,6.000000,6,6,6.000000,6.000000,6,6
unique,NaN,6,2,NaN,NaN,3,2
top,NaN,Laptop,Electronics,NaN,NaN,Bogota,True
freq,NaN,1,4,NaN,NaN,3,5
mean,103.500000,NaN,NaN,323.416667,5.166667,NaN,NaN
std,1.870829,NaN,NaN,441.811093,2.926887,NaN,NaN
min,101.000000,NaN,NaN,25.500000,2.000000,NaN,NaN
25%,102.250000,NaN,NaN,71.250000,3.250000,NaN,NaN
50%,103.500000,NaN,NaN,185.000000,4.500000,NaN,NaN
75%,104.750000,NaN,NaN,280.000000,6.500000,NaN,NaN
max,106.000000,NaN,NaN,1200.000000,10.000000,NaN,NaN

In [47]:
sales_df.nunique()

sale_id     6
product     6
category    2
price       6
quantity    6
city        3
in_stock    2
dtype: int64

## 7. Selecting one column and multiple columns

Selecting data is one of the most common things you will do.

- Use `df["column_name"]` for one column
- Use `df[["col1", "col2"]]` for multiple columns

Notice that selecting one column returns a `Series`, while selecting multiple columns returns a `DataFrame`.

In [48]:
print("One column (Series):\n")
print(sales_df["product"])
print("\nMultiple columns (DataFrame):\n")
sales_df[["product", "price", "quantity"]]

One column (Series):

0      Laptop
1       Mouse
2        Desk
3     Monitor
4       Chair
5    Keyboard
Name: product, dtype: str

Multiple columns (DataFrame):

    product   price  quantity
0    Laptop  1200.0         2
1     Mouse    25.5        10
2      Desk   300.0         3
3   Monitor   220.0         4
4     Chair   150.0         5
5  Keyboard    45.0         7

## 8. Basic filtering with simple conditions

Filtering means keeping only the rows that match a condition.

Examples:

- rows where `price > 30`
- rows where `city == "Bogota"`
- rows that match two conditions at the same time

In [58]:
expensive_items = sales_df[sales_df["price"] > 30]
bogota_sales = sales_df[sales_df["city"] == "Bogota"]
electronics_in_stock = sales_df[(sales_df["category"] == "Electronics") & (sales_df["in_stock"])]

print("Rows where price > 30:\n")
print(expensive_items)
print("\nRows where city == 'Bogota':\n")
print(bogota_sales)
print("\nElectronics that are in stock:\n")
electronics_in_stock

Rows where price > 30:

   sale_id   product     category   price  quantity      city  in_stock
0      101    Laptop  Electronics  1200.0         2    Bogota      True
2      103      Desk    Furniture   300.0         3    Bogota     False
3      104   Monitor  Electronics   220.0         4  Medellin      True
4      105     Chair    Furniture   150.0         5      Cali      True
5      106  Keyboard  Electronics    45.0         7    Bogota      True

Rows where city == 'Bogota':

   sale_id   product     category   price  quantity    city  in_stock
0      101    Laptop  Electronics  1200.0         2  Bogota      True
2      103      Desk    Furniture   300.0         3  Bogota     False
5      106  Keyboard  Electronics    45.0         7  Bogota      True

Electronics that are in stock:

   sale_id   product     category   price  quantity      city  in_stock
0      101    Laptop  Electronics  1200.0         2    Bogota      True
1      102     Mouse  Electronics    25.5        10      Cali      True
3      104   Monitor  Electronics   220.0         4  Medellin      True
5      106  Keyboard  Electronics    45.0         7    Bogota      True

## 9. Sorting values

Sorting helps you organize data so patterns are easier to spot.

Use `sort_values()` and choose:

- the column to sort by
- whether you want ascending or descending order

In [62]:
sales_df.sort_values(["category","price"], ascending=False)

   sale_id   product     category   price  quantity      city  in_stock
2      103      Desk    Furniture   300.0         3    Bogota     False
4      105     Chair    Furniture   150.0         5      Cali      True
0      101    Laptop  Electronics  1200.0         2    Bogota      True
3      104   Monitor  Electronics   220.0         4  Medellin      True
5      106  Keyboard  Electronics    45.0         7    Bogota      True
1      102     Mouse  Electronics    25.5        10      Cali      True

In [63]:
print("Sorted by price (highest first):\n")
print(sales_df.sort_values("price", ascending=False))
print("\nSorted by category, then by price within each category:\n")
sales_df.sort_values(["category", "price"], ascending=[True, False])

Sorted by price (highest first):

   sale_id   product     category   price  quantity      city  in_stock
0      101    Laptop  Electronics  1200.0         2    Bogota      True
2      103      Desk    Furniture   300.0         3    Bogota     False
3      104   Monitor  Electronics   220.0         4  Medellin      True
4      105     Chair    Furniture   150.0         5      Cali      True
5      106  Keyboard  Electronics    45.0         7    Bogota      True
1      102     Mouse  Electronics    25.5        10      Cali      True

Sorted by category, then by price within each category:

   sale_id   product     category   price  quantity      city  in_stock
0      101    Laptop  Electronics  1200.0         2    Bogota      True
3      104   Monitor  Electronics   220.0         4  Medellin      True
5      106  Keyboard  Electronics    45.0         7    Bogota      True
1      102     Mouse  Electronics    25.5        10      Cali      True
2      103      Desk    Furniture   300.0         3    Bogota     False
4      105     Chair    Furniture   150.0         5      Cali      True

## 10. Reading a CSV file with pandas

In real projects, your data will often come from a file. A very common format is CSV.

Below, we create a small local CSV file so the notebook runs anywhere. Later, you can replace the path with a Kaggle dataset or another CSV on your computer.

In [65]:
csv_path = "sample_store_data.csv"  # Later, replace this with your own CSV path.

csv_example = pd.DataFrame(
    {
        "order_id": [201, 202, 203, 204, 205],
        "customer": ["Ana", "Luis", "Marta", "Diego", "Elena"],
        "product": ["Book", "Tablet", "Notebook", "Headphones", "Mouse"],
        "price": [18, 450, 6, 80, 20],
        "quantity": [2, 1, 5, 1, 3],
    }
)

# Save a local CSV so we can practice reading a file.
csv_example.to_csv(csv_path, index=False)

print(f"Sample CSV saved to: {csv_path}")
csv_example

Sample CSV saved to: sample_store_data.csv

   order_id customer     product  price  quantity
0       201      Ana        Book     18         2
1       202     Luis      Tablet    450         1
2       203    Marta    Notebook      6         5
3       204    Diego  Headphones     80         1
4       205    Elena       Mouse     20         3

In [66]:
orders_df = pd.read_csv(csv_path)

print("Loaded from CSV:\n")
print(orders_df.head())
print("\nQuick inspection:")
print("Shape:", orders_df.shape)
print("Columns:", list(orders_df.columns))

Loaded from CSV:

   order_id customer     product  price  quantity
0       201      Ana        Book     18         2
1       202     Luis      Tablet    450         1
2       203    Marta    Notebook      6         5
3       204    Diego  Headphones     80         1
4       205    Elena       Mouse     20         3

Quick inspection:
Shape: (5, 5)
Columns: ['order_id', 'customer', 'product', 'price', 'quantity']

## Practice section

Try these short exercises on your own. Use either `sales_df` or `orders_df`.

1. Show the first 4 rows of `orders_df`.
2. Select only the `product` and `price` columns from `sales_df`.
3. Filter `sales_df` to keep only rows where `quantity >= 5`.
4. Sort `orders_df` by `price` from lowest to highest.
5. Find only the rows in `sales_df` where `city` is `"Cali"`.

In [ ]:
# Try your practice exercises here.
# Example:
# orders_df.head(4)

## Mini challenge setup

Here is a fresh dataset for one final task.

In [67]:
challenge_df = pd.DataFrame(
    {
        "student": ["Ana", "Luis", "Marta", "Jorge", "Sofia", "Camilo"],
        "hours_studied": [5, 2, 7, 4, 6, 3],
        "score": [78, 60, 91, 73, 88, 67],
        "passed": [True, False, True, True, True, False],
    }
)

challenge_df

  student  hours_studied  score  passed
0     Ana              5     78    True
1    Luis              2     60   False
2   Marta              7     91    True
3   Jorge              4     73    True
4   Sofia              6     88    True
5  Camilo              3     67   False

## Mini challenge

Use `challenge_df` and do the following:

1. Inspect the dataset with at least three pandas tools such as `head()`, `shape`, `columns`, or `info()`.
2. Select only the `student` and `score` columns.
3. Filter the rows where `score >= 75`.
4. Sort the filtered result by `score` from highest to lowest.
5. Bonus: keep only students who passed **and** studied at least 5 hours.

In [86]:
# Write your mini challenge solution here.

# Step 1: inspect the dataset

print(challenge_df.info(), "\n")
print(challenge_df.head(), "\n")
print(challenge_df.columns, "\n")

# Step 2: select columns

selection_df = challenge_df[["student","score"]]
print(selection_df, "\n")

# Step 3: filter rows

filtered_df = selection_df[selection_df["score"] >= 75]
print(filtered_df, "\n")

# Step 4: sort the result

filtered_df.sort_values(["score"], ascending = False)

# Bonus

filtered_bonus_df = challenge_df[(challenge_df["hours_studied"] >= 5) & (challenge_df["passed"] == True)]
filtered_bonus_df

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   student        6 non-null      str
 1   hours_studied  6 non-null      int64
 2   score          6 non-null      int64
 3   passed         6 non-null      bool
dtypes: bool(1), int64(2), str(1)
memory usage: 282.0 bytes
None

  student  hours_studied  score  passed
0     Ana              5     78    True
1    Luis              2     60   False
2   Marta              7     91    True
3   Jorge              4     73    True
4   Sofia              6     88    True

Index(['student', 'hours_studied', 'score', 'passed'], dtype='str')

  student  score
0     Ana     78
1    Luis     60
2   Marta     91
3   Jorge     73
4   Sofia     88
5  Camilo     67

  student  score
0     Ana     78
2   Marta     91
4   Sofia     88

  student  hours_studied  score  passed
0     Ana              5     78    True
2   Marta              7     91    True
4   Sofia              6     88    True

## Recap

In this notebook, you practiced the core pandas actions that appear again and again in real data work: creating tables, loading data, inspecting structure, selecting columns, filtering rows, and sorting values.

## Key takeaways

- pandas is a powerful library for working with tabular data
- a `Series` is one-dimensional, while a `DataFrame` is a full table
- rows, columns, and indexes are the basic building blocks of pandas data
- `head()`, `shape`, `columns`, `dtypes`, `info()`, and `describe()` help you understand a dataset quickly
- selecting, filtering, and sorting are some of the most important beginner pandas skills
- the same workflow works whether your data is created in Python or loaded from a CSV file